/**
 * src/research/research-dossier-note.ts — PURE builder: a ResearchDossier → an Obsidian
 * "research_dossier" note proposal. This is what makes a research output "usable across HartOS":
 * the dossier lands in the meaning-layer vault (gated, Hart-approved) where Rinnegan compiles it
 * into the LLM Ask's briefing and Prophet/awareness can reason over it — knowledge, not raw facts.
 *
 * Descriptive only: an ObsidianNoteProposal is non-executable until Hart approves AND the writer is
 * armed (HARTOS_OBSIDIAN_VAULT_PATH + ALLOW_OBSIDIAN_WRITE). No fs / clock — `now` is injected.
 * Honesty floor: the note carries the dossier's own confidence + its unknowns, never laundering a
 * thin result as a confident one.
 */

import type { ObsidianNoteProposal } from "../obsidian/obsidian-types.js";
import type { ResearchDossier, ResearchConfidence } from "./research-synthesis.js";

/** Map dossier confidence (which has "unknown") onto the note's (high|medium|low) — unknown ⇒ low. */
function noteConfidence(c: ResearchConfidence): "high" | "medium" | "low" {
  return c === "high" ? "high" : c === "medium" ? "medium" : "low";
}

export function researchDossierNote(dossier: ResearchDossier, now: string): ObsidianNoteProposal {
  const day = now.slice(0, 10);
  const body = [
    `# Research Dossier — ${dossier.question}`,
    "",
    `**Confidence: ${dossier.confidence.toUpperCase()}** · shape: ${dossier.shape} · ${day}`,
    "",
    "## Executive summary",
    ...dossier.executiveSummary.map((l) => `- ${l}`),
    "",
    "## Key findings",
    ...(dossier.keyFindings.length
      ? dossier.keyFindings.map(
          (f) =>
            `- **${f.question}**\n    - ${f.finding}\n    - sources: ${f.sources.join(", ")} · confidence: ${f.confidence}`,
        )
      : ["- _No findings gathered yet — see open questions below._"]),
    "",
    "## Reusable knowledge (usable across HartOS)",
    ...(dossier.knowledgeItems.length
      ? dossier.knowledgeItems.map(
          (k) => `- ${k.claim}\n    - applies to: ${k.appliesTo.join("; ")} · sources: ${k.sources.join(", ")} · ${k.confidence}`,
        )
      : ["- _No reusable knowledge yet — needs corroborated findings._"]),
    "",
    "## Open questions (honest unknowns)",
    ...(dossier.unknowns.length ? dossier.unknowns.map((u) => `- ${u}`) : ["- _None — every sub-question was answered._"]),
    "",
    "## Sources",
    ...(dossier.sources.length
      ? dossier.sources.map((s) => `- ${s.title} (\`${s.ref}\`${s.asOf ? `, as of ${s.asOf}` : ""})`)
      : ["- _No sources gathered._"]),
    "",
    "_Generated by the Research Agent. Findings are gathered, never fabricated; this note is the meaning-layer record._",
  ].join("\n");

  return {
    title: `Research — ${dossier.question}`.slice(0, 120),
    folder: "HartOS/Research Dossiers",
    noteType: "research_dossier",
    tags: ["hartos", "research", dossier.shape, dossier.confidence],
    body,
    sources: dossier.sources.map((s) => s.ref),
    confidence: noteConfidence(dossier.confidence),
    reason: "Research synthesis kept in the vault as reusable knowledge for the fleet (LLM Ask / Rinnegan / future research).",
    // Knowledge ages — nudge a review in ~90 days so Wolverine's stale-note detector can flag it.
    reviewBy: null,
    relatedAgents: ["Research"],
    relatedProposals: [],
    createdAt: now,
  };
}
