/**
 * src/research/research-dossier-note.ts — PURE builder: a ResearchDossier → an Obsidian
 * "research_dossier" note proposal. This is what makes a research output "usable across HartOS":
 * the dossier lands in the meaning-layer vault (gated, Hart-approved) where Rinnegan compiles it
 * into the LLM Ask's briefing and Prophet/awareness can reason over it — knowledge, not raw facts.
 *
 * Descriptive only: an ObsidianNoteProposal is non-executable until Hart approves AND the writer is
 * armed (HARTOS_OBSIDIAN_VAULT_PATH + ALLOW_OBSIDIAN_WRITE). No fs / clock — `now` is injected.
 * Honesty floor: the note carries the dossier's own confidence + its unknowns, never laundering a
 * thin result as a confident one.
 *
 * CITATIONS render READABLE: findings cite by compact numbers ([1][2]); the Sources section is a
 * numbered list of markdown links whose VISIBLE text is the source's domain/title (Gemini grounding
 * gives e.g. "mas.gov.sg"), with the raw URL as the hidden href — never the giant opaque
 * grounding-redirect URL inline.
 */

import type { ObsidianNoteProposal } from "../obsidian/obsidian-types.js";
import type { ResearchDossier, ResearchConfidence } from "./research-synthesis.js";

/** Map dossier confidence (which has "unknown") onto the note's (high|medium|low) — unknown ⇒ low. */
function noteConfidence(c: ResearchConfidence): "high" | "medium" | "low" {
  return c === "high" ? "high" : c === "medium" ? "medium" : "low";
}

function isUrl(ref: string): boolean {
  return /^https?:\/\//i.test(ref);
}

/**
 * Readable label for a source. Prefer the provider title (Gemini grounding gives the real source
 * domain, e.g. "mas.gov.sg"); else the URL hostname; else the ref. Never the opaque redirect URL.
 */
function sourceLabel(title: string, ref: string): string {
  const t = (title ?? "").trim();
  if (t && !isUrl(t)) return t.slice(0, 80);
  if (isUrl(ref)) {
    try {
      return new URL(ref).hostname.replace(/^www\./, "");
    } catch {
      /* fall through */
    }
  }
  return (t || ref).slice(0, 80);
}

export function researchDossierNote(dossier: ResearchDossier, now: string): ObsidianNoteProposal {
  const day = now.slice(0, 10);

  // De-dup sources by ref, in first-seen order, and number them. Findings/knowledge then cite by
  // those numbers, so the prose stays readable and every URL appears exactly once in ## Sources.
  const uniqueSources: { ref: string; title: string; asOf: string | null }[] = [];
  const refToNum = new Map<string, number>();
  for (const s of dossier.sources) {
    if (!refToNum.has(s.ref)) {
      refToNum.set(s.ref, uniqueSources.length + 1);
      uniqueSources.push(s);
    }
  }
  /** Compact numbered citation for a finding's refs, e.g. "[1][3]". "—" when none resolve. */
  const cite = (refs: string[]): string => {
    const nums = [...new Set(refs.map((r) => refToNum.get(r)).filter((n): n is number => typeof n === "number"))].sort(
      (a, b) => a - b,
    );
    return nums.length ? nums.map((n) => `[${n}]`).join("") : "—";
  };

  const body = [
    `# Research Dossier — ${dossier.question}`,
    "",
    `**Confidence: ${dossier.confidence.toUpperCase()}** · shape: ${dossier.shape} · ${day}`,
    "",
    "## Executive summary",
    ...dossier.executiveSummary.map((l) => `- ${l}`),
    "",
    "## Key findings",
    ...(dossier.keyFindings.length
      ? dossier.keyFindings.flatMap((f) => [
          `### ${f.question}`,
          "",
          f.detail || f.finding,
          "",
          `_sources: ${cite(f.sources)} · confidence: ${f.confidence}_`,
          "",
        ])
      : ["- _No findings gathered yet — see open questions below._"]),
    "",
    "## Reusable knowledge (usable across HartOS)",
    ...(dossier.knowledgeItems.length
      ? dossier.knowledgeItems.map(
          (k) => `- ${k.claim}\n    - applies to: ${k.appliesTo.join("; ")} · sources: ${cite(k.sources)} · ${k.confidence}`,
        )
      : ["- _No reusable knowledge yet — needs corroborated findings._"]),
    "",
    "## Open questions (honest unknowns)",
    ...(dossier.unknowns.length ? dossier.unknowns.map((u) => `- ${u}`) : ["- _None — every sub-question was answered._"]),
    "",
    "## Sources",
    ...(uniqueSources.length
      ? uniqueSources.map((s, i) => {
          const n = i + 1;
          const label = sourceLabel(s.title, s.ref);
          const asOf = s.asOf ? ` — as of ${s.asOf.slice(0, 10)}` : "";
          // Markdown link: visible text = readable domain/title; href = the URL (redirect still
          // resolves on click). A non-URL ref (e.g. an uncited-grounding sentinel) renders plain.
          return isUrl(s.ref) ? `${n}. [${label}](${s.ref})${asOf}` : `${n}. ${label}${asOf}`;
        })
      : ["- _No sources gathered._"]),
    "",
    "_Generated by the Research Agent. Findings are gathered, never fabricated; this note is the meaning-layer record._",
  ].join("\n");

  return {
    title: `Research — ${dossier.question}`.slice(0, 120),
    folder: "HartOS/Research Dossiers",
    noteType: "research_dossier",
    tags: ["hartos", "research", dossier.shape, dossier.confidence],
    body,
    sources: dossier.sources.map((s) => s.ref),
    confidence: noteConfidence(dossier.confidence),
    reason: "Research synthesis kept in the vault as reusable knowledge for the fleet (LLM Ask / Rinnegan / future research).",
    // Knowledge ages — nudge a review in ~90 days so Wolverine's stale-note detector can flag it.
    reviewBy: null,
    relatedAgents: ["Research"],
    relatedProposals: [],
    createdAt: now,
  };
}
