/**
 * src/beezulbub/batch-digest.ts
 *
 * Batch digestion of multiple local repositories.
 * Processes all repos, continues on failure, ranks results.
 */

import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import type { BatchConfig, BatchDigestResult, BatchDigestResultEntry, RepoDigest } from "./types.js";
import { digestLocalRepo } from "./digest.js";

export async function loadBatchConfig(configPath: string): Promise<BatchConfig> {
  if (!existsSync(configPath)) {
    throw new Error(`Batch config not found: ${configPath}`);
  }
  const raw = await readFile(configPath, "utf8");
  return JSON.parse(raw) as BatchConfig;
}

export async function runBatchDigest(config: BatchConfig): Promise<BatchDigestResult> {
  const { target, repos } = config;
  const timestamp = new Date().toISOString();
  const results: BatchDigestResultEntry[] = [];

  for (const repo of repos) {
    if (!repo.localPath) {
      results.push({
        repo,
        status: "skipped",
        error: "No localPath provided. Clone the repo first.",
      });
      continue;
    }

    if (!existsSync(repo.localPath)) {
      results.push({
        repo,
        status: "skipped",
        error: `Path not found: ${repo.localPath}. Clone first.`,
      });
      continue;
    }

    try {
      const digest = await digestLocalRepo({
        localPath: repo.localPath,
        targetCapability: target,
      });
      results.push({ repo, digest, status: "digested" });
    } catch (err) {
      results.push({
        repo,
        status: "failed",
        error: err instanceof Error ? err.message.slice(0, 200) : "Unknown error",
      });
    }
  }

  // Build ranking from digested repos
  const digested = results.filter((r): r is BatchDigestResultEntry & { digest: RepoDigest } =>
    r.status === "digested" && r.digest !== undefined
  );
  const ranking = digested
    .map((r) => ({
      name: r.repo.name,
      verdict: r.digest.recommendedVerdict,
      overall: r.digest.score.overall,
    }))
    .sort((a, b) => b.overall - a.overall);

  const topCandidate = ranking[0]?.name ?? null;

  // Determine overall batch status
  const failedCount = results.filter((r) => r.status === "failed").length;
  const digestedCount = results.filter((r) => r.status === "digested").length;
  const status: BatchDigestResult["status"] =
    digestedCount === 0 ? "failed" : failedCount > 0 ? "partial" : "completed";

  // Build recommendation
  const devourCandidates = ranking.filter((r) =>
    r.verdict === "DEVOUR" || r.verdict === "PARTIAL_DEVOUR"
  );
  const rejectCandidates = ranking.filter((r) => r.verdict.startsWith("REJECT"));

  const recommendation =
    devourCandidates.length === 0
      ? `No devourable candidates found in this batch. ` +
        `${rejectCandidates.length} rejected. Try different candidates.`
      : `Best candidate: ${devourCandidates[0]!.name} (${devourCandidates[0]!.verdict}, ` +
        `score: ${devourCandidates[0]!.overall}/10). ` +
        `${devourCandidates.length} devourable, ${rejectCandidates.length} rejected.`;

  return {
    target,
    timestamp,
    status,
    results,
    ranking,
    topCandidate,
    recommendation,
  };
}

export function formatBatchReport(batch: BatchDigestResult): string {
  const lines = [
    `# Beezulbub Batch Report: ${batch.target}`,
    ``,
    `Status: ${batch.status}`,
    `Timestamp: ${batch.timestamp}`,
    `Repos: ${batch.results.length}`,
    ``,
    `## Ranking`,
    ``,
  ];

  if (batch.ranking.length === 0) {
    lines.push("No repos digested successfully.");
  } else {
    for (const [i, r] of batch.ranking.entries()) {
      lines.push(`${i + 1}. **${r.name}** — ${r.verdict} (${r.overall}/10)`);
    }
  }

  lines.push(``);
  lines.push(`## Results`);
  lines.push(``);
  for (const r of batch.results) {
    if (r.status === "digested" && r.digest) {
      lines.push(`### ${r.repo.name} — ${r.digest.recommendedVerdict}`);
      lines.push(`Score: ${r.digest.score.overall}/10`);
      lines.push(`License: ${r.digest.license ?? "NONE"} (${r.digest.licenseRisk})`);
      lines.push(`Poison: ${r.digest.poisonFlags.length} flag(s)`);
      lines.push(`Capabilities: ${r.digest.usefulCapabilities.map((c) => c.id).join(", ") || "none"}`);
      lines.push(``);
    } else {
      lines.push(`### ${r.repo.name} — ${r.status.toUpperCase()}`);
      if (r.error) lines.push(`Error: ${r.error}`);
      lines.push(``);
    }
  }

  lines.push(`## Recommendation`);
  lines.push(``);
  lines.push(batch.recommendation);
  lines.push(``);
  lines.push(`---`);
  lines.push(`Generated by HartOS Beezulbub Phase 11B`);

  return lines.join("\n") + "\n";
}
