/**
 * src/beezulbub/capability-dossier-note.ts — PURE builder: a Beezulbub scout result → an Obsidian
 * "capability_dossier" note. This closes the loop for CAPABILITY intelligence the same way the
 * research dossier does for research: "what OSS should we absorb for <target>?" becomes reusable
 * vault knowledge that Rinnegan compiles into the LLM Ask's briefing.
 *
 * Descriptive only: an ObsidianNoteProposal is non-executable until Hart approves + the writer is
 * armed. Honesty floor: a scout DISCOVERS candidates; it has not digested/poison-scanned them, so
 * confidence is capped (live+candidates → medium, otherwise low) and the note says so. Doctrine:
 * Beezulbub proposes; it never auto-copies code. No fs / clock — `now` is injected.
 */

import type { BeezulbubScoutResult } from "./types.js";
import type { ObsidianNoteProposal, NoteConfidence } from "../obsidian/obsidian-types.js";

function scoutConfidence(result: BeezulbubScoutResult): NoteConfidence {
  // A live scout with real candidates is a real (if shallow) read; fixtures/empty are weaker.
  if (result.mode === "live" && result.candidates.length > 0) return "medium";
  return "low";
}

export function capabilityScoutNote(result: BeezulbubScoutResult, now: string): ObsidianNoteProposal {
  const day = now.slice(0, 10);
  const confidence = scoutConfidence(result);
  const ranked = [...result.candidates].sort((a, b) => b.estimatedValue - a.estimatedValue);

  const body = [
    `# Capability Scout — ${result.target}`,
    "",
    `**Mode: ${result.mode.toUpperCase()}** · confidence: ${confidence} · ${day}`,
    "",
    "## Recommendation",
    result.recommendation,
    "",
    `## Candidates (${ranked.length}, ranked by value)`,
    ...(ranked.length
      ? ranked.flatMap((c, i) => [
          `### ${i + 1}. ${c.name} — ${c.estimatedValue}/10`,
          `- license: ${c.licenseGuess ?? "unknown"} · stale-risk: ${c.staleRisk}`,
          c.sourceUrl ? `- source: ${c.sourceUrl}` : `- source: (local) ${c.localPath ?? "n/a"}`,
          `- why: ${c.reason}`,
          ...(c.notes ? [`- notes: ${c.notes}`] : []),
          "",
        ])
      : ["- _No candidates found — try a different target or enable live search._", ""]),
    "## How to absorb (next step)",
    "Beezulbub PROPOSES; it never auto-copies code. To go deeper on a pick: clone it and run",
    "`beezulbub:digest` for a full poison/license/security scan, a 7-dim score, a DEVOUR/REJECT",
    "verdict, and a HartOS adaptation plan. Folding anything into a build plan requires Hart's approval.",
    "",
    "_Generated by Beezulbub (capability scout). Candidates are discovered, not yet digested — advisory only._",
  ].join("\n");

  return {
    title: `Capability Scout — ${result.target}`.slice(0, 120),
    folder: "HartOS/Capability Scout",
    noteType: "capability_dossier",
    tags: ["hartos", "beezulbub", "capability-scout", result.target, result.mode],
    body,
    sources: ranked.map((c) => c.sourceUrl).filter((u): u is string => typeof u === "string" && u.length > 0),
    confidence,
    reason: `Beezulbub capability scout for "${result.target}" — reusable knowledge on what OSS to absorb (LLM Ask / Rinnegan / Factory).`,
    reviewBy: null,
    relatedAgents: ["Beezulbub"],
    relatedProposals: [],
    createdAt: now,
  };
}
