/**
 * src/beezulbub/pack-conflicts.ts
 *
 * Basic conflict detection between packs.
 * Manifest-based analysis — no runtime execution needed.
 */

import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import type { PackManifest } from "./pack-types.js";

// ─── Extended manifest with contracts ─────────────────────────────────────────

export interface PackContracts {
  commands?: string[];
  routes?: string[];
  envVars?: string[];
  tables?: string[];
  migrations?: string[];
  providerBindings?: string[];
}

export interface PackManifestWithContracts extends PackManifest {
  contracts?: PackContracts;
}

// ─── Conflict types ───────────────────────────────────────────────────────────

export interface ConflictItem {
  type: "duplicate_name" | "duplicate_command" | "duplicate_route" | "duplicate_env_var"
      | "duplicate_table" | "duplicate_migration" | "duplicate_provider_binding"
      | "duplicate_capability_id";
  value: string;
  packs: string[];
}

export interface ConflictReport {
  packsChecked: string[];
  conflicts: ConflictItem[];
  status: "clean" | "conflicts_found";
  summary: string;
}

// ─── Conflict detector ────────────────────────────────────────────────────────

export async function detectConflicts(packPaths: string[]): Promise<ConflictReport> {
  const manifests: Array<{ name: string; manifest: PackManifestWithContracts }> = [];

  for (const packPath of packPaths) {
    const manifestPath = path.join(packPath, "pack.manifest.json");
    if (!existsSync(manifestPath)) continue;
    try {
      const raw = await readFile(manifestPath, "utf8");
      const manifest = JSON.parse(raw) as PackManifestWithContracts;
      manifests.push({ name: manifest.packName, manifest });
    } catch { /* skip corrupt */ }
  }

  const conflicts: ConflictItem[] = [];

  // 1. Duplicate pack names
  const nameMap = new Map<string, string[]>();
  for (const { name } of manifests) {
    const existing = nameMap.get(name) ?? [];
    existing.push(name);
    nameMap.set(name, existing);
  }
  for (const [name, packs] of nameMap) {
    if (packs.length > 1) {
      conflicts.push({ type: "duplicate_name", value: name, packs });
    }
  }

  // 2. Duplicate capability IDs
  const capMap = new Map<string, string[]>();
  for (const { name, manifest } of manifests) {
    for (const cap of manifest.capabilities) {
      const existing = capMap.get(cap) ?? [];
      existing.push(name);
      capMap.set(cap, existing);
    }
  }
  for (const [cap, packs] of capMap) {
    if (packs.length > 1) {
      conflicts.push({ type: "duplicate_capability_id", value: cap, packs });
    }
  }

  // 3. Contract-level conflicts
  type ContractKey = keyof PackContracts;
  const conflictTypes: Array<{ key: ContractKey; type: ConflictItem["type"] }> = [
    { key: "commands", type: "duplicate_command" },
    { key: "routes", type: "duplicate_route" },
    { key: "envVars", type: "duplicate_env_var" },
    { key: "tables", type: "duplicate_table" },
    { key: "migrations", type: "duplicate_migration" },
    { key: "providerBindings", type: "duplicate_provider_binding" },
  ];

  for (const { key, type } of conflictTypes) {
    const seen = new Map<string, string[]>();
    for (const { name, manifest } of manifests) {
      const values = manifest.contracts?.[key] ?? [];
      for (const val of values) {
        const existing = seen.get(val) ?? [];
        existing.push(name);
        seen.set(val, existing);
      }
    }
    for (const [val, packs] of seen) {
      if (packs.length > 1) {
        conflicts.push({ type, value: val, packs });
      }
    }
  }

  const status = conflicts.length === 0 ? "clean" : "conflicts_found";
  const summary = status === "clean"
    ? `No conflicts detected across ${manifests.length} pack(s).`
    : `${conflicts.length} conflict(s) found across ${manifests.length} pack(s).`;

  return {
    packsChecked: manifests.map((m) => m.name),
    conflicts,
    status,
    summary,
  };
}

export function formatConflictReport(report: ConflictReport): string {
  const icon = report.status === "clean" ? "✅" : "⚠️";
  const lines = [
    `# Beezulbub Pack Conflict Report`,
    ``,
    `${icon} ${report.summary}`,
    ``,
    `Packs checked: ${report.packsChecked.join(", ") || "none"}`,
    ``,
  ];

  if (report.conflicts.length === 0) {
    lines.push(`No conflicts detected.`);
  } else {
    lines.push(`## Conflicts`);
    lines.push(``);
    for (const c of report.conflicts) {
      lines.push(`- **${c.type}**: \`${c.value}\` found in: ${c.packs.join(", ")}`);
    }
  }

  lines.push(``);
  lines.push(`---`);
  lines.push(`Generated by HartOS Beezulbub Phase 11D`);

  return lines.join("\n") + "\n";
}
