/**
 * src/beezulbub/pack-implementation-report.ts
 *
 * Format reports for pack implementation (Phase 11E).
 */

import type { ImplementResult } from "./pack-implementation-types.js";

export function formatImplementReport(result: ImplementResult): string {
  const icon = result.status === "implemented" ? "✅" : "❌";
  const lines = [
    `# Pack Implementation Report: ${result.packName}`,
    ``,
    `${icon} Status: **${result.status}**`,
    ``,
    `${result.message}`,
    ``,
  ];

  if (result.status === "implemented") {
    lines.push(`## Capability type`);
    lines.push(``);
    lines.push(`${result.capabilityType}`);
    lines.push(``);

    lines.push(`## Files generated (${result.filesGenerated.length})`);
    lines.push(``);
    for (const f of result.filesGenerated) {
      lines.push(`- ${f}`);
    }
    lines.push(``);

    lines.push(`## HartOS doctrine applied`);
    lines.push(``);
    lines.push(`- ✓ HartOS-native scaffold — no third-party code copied`);
    lines.push(`- ✓ All stubs throw "not yet implemented"`);
    lines.push(`- ✓ No hardcoded secrets`);
    lines.push(`- ✓ Data contracts reference Supabase RLS`);
    lines.push(`- ✓ Safety scan passed`);
    lines.push(``);

    lines.push(`## Next steps`);
    lines.push(``);
    lines.push(`1. Review generated stubs in ${result.packPath}`);
    lines.push(`2. Implement the stubs following adaptation-plan.md`);
    lines.push(`3. Run: npm run beezulbub:pack-verify -- --pack=${result.packPath}`);
    lines.push(`4. If verified: npm run beezulbub:pack-promote -- --pack=${result.packPath} --to=verified --approve-promote`);
  }

  if (result.status.startsWith("blocked_")) {
    lines.push(`## To unblock`);
    lines.push(``);
    if (result.status === "blocked_missing_approval") {
      lines.push(`Set BEEZULBUB_ALLOW_PACK_IMPLEMENT=true and pass --approve-implementation flag.`);
    } else if (result.status === "blocked_bad_status") {
      lines.push(`Pack must be in 'skeleton' status to implement.`);
    } else if (result.status === "blocked_bad_verdict") {
      lines.push(`Only DEVOUR and PARTIAL_DEVOUR packs can be implemented.`);
    } else if (result.status === "blocked_no_provenance") {
      lines.push(`Run beezulbub:pack-generate first to record provenance.`);
    }
  }

  lines.push(``);
  lines.push(`---`);
  lines.push(`Generated by HartOS Beezulbub Phase 11E`);

  return lines.join("\n") + "\n";
}
