/**
 * src/beezulbub/pack-generator.ts
 *
 * Generate HartOS-compatible pack skeletons from approved Beezulbub digests.
 *
 * Doctrine:
 *   - Generate skeleton. Do not copy architecture. Do not copy code blindly.
 *   - All generated content is HartOS-shaped stubs/docs.
 *   - No third-party source code is copied.
 *   - No secrets in generated files.
 */

import { readdir, readFile, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import type {
  PackGenerateOptions,
  PackGenerateResult,
  PackManifest,
  ScoreJson,
} from "./pack-types.js";
import { scanPackContent, formatSafetyIssues } from "./pack-safety.js";
import { registerPackGenerated } from "./capability-registry.js";
import { recordProvenance } from "./provenance-ledger.js";

const DEVOURABLE_VERDICTS = new Set(["DEVOUR", "PARTIAL_DEVOUR"]);
const DEFAULT_PACKS_DIR = "packs";
const DEFAULT_REGISTRY_PATH = "capabilities/capability-registry.json";
const DEFAULT_LEDGER_PATH = "capabilities/provenance-ledger.json";

// ─── Load candidate ───────────────────────────────────────────────────────────

async function loadLatestScore(reportsDir: string): Promise<ScoreJson | null> {
  if (!existsSync(reportsDir)) return null;
  const files = await readdir(reportsDir);

  // Prefer batch JSON
  const batchFiles = files
    .filter((f) => f.startsWith("batch-digest-") && f.endsWith(".json"))
    .sort().reverse();
  if (batchFiles.length > 0) {
    try {
      const raw = await readFile(path.join(reportsDir, batchFiles[0]!), "utf8");
      const b = JSON.parse(raw) as ScoreJson;
      if (b.ranking && b.ranking.length > 0) {
        const top = b.ranking[0]!;
        return { repoName: top.name, verdict: top.verdict, score: { overall: top.overall }, capabilities: [] };
      }
    } catch { /* try next */ }
  }

  const scoreFiles = files
    .filter((f) => f.startsWith("score-") && f.endsWith(".json"))
    .sort().reverse();
  if (scoreFiles.length > 0) {
    try {
      const raw = await readFile(path.join(reportsDir, scoreFiles[0]!), "utf8");
      return JSON.parse(raw) as ScoreJson;
    } catch { return null; }
  }

  return null;
}

// ─── File generators ──────────────────────────────────────────────────────────

function generateManifest(candidate: ScoreJson, capability: string, reportsDir: string): PackManifest {
  const caps = candidate.capabilities && candidate.capabilities.length > 0
    ? candidate.capabilities
    : [capability];

  return {
    packName: capability,
    packVersion: "0.1.0",
    status: "skeleton",
    source: {
      digestId: `digest-from-${reportsDir}`,
      repoName: candidate.repoName ?? "unknown",
      sourceUrl: null,
      verdict: candidate.verdict ?? "UNKNOWN",
      scoreOverall: candidate.score?.overall ?? 0,
      license: candidate.license ?? null,
    },
    capabilities: caps,
    hartosCompatibility: {
      requiresSupabase: false,
      requiresTrigger: false,
      requiresCloudflare: false,
      requiresTelegram: false,
      requiresApprovalGate: true,
    },
    absorb: [`${capability} component patterns`, "HartOS-adapted stubs"],
    reject: [
      "Foreign auth model",
      "Foreign database schema",
      "Foreign deployment assumptions",
    ],
    requiredTests: [
      "pack contract test (manifest valid)",
      "no secret report test",
      "smoke plan exists",
    ],
    createdAt: new Date().toISOString(),
  };
}

function generateReadme(capability: string, manifest: PackManifest): string {
  return [
    `# Pack: ${capability}`,
    ``,
    `**Status:** ${manifest.status} — implementation stub only.`,
    ``,
    `## Overview`,
    ``,
    `This pack skeleton was generated by HartOS Beezulbub Phase 11C.`,
    `It contains structure, docs, and test stubs — NO third-party code.`,
    ``,
    `## Source`,
    ``,
    `- Repo: ${manifest.source.repoName}`,
    `- Verdict: ${manifest.source.verdict} (${manifest.source.scoreOverall}/10)`,
    `- License: ${manifest.source.license ?? "unknown"}`,
    ``,
    `## Capabilities`,
    ``,
    ...manifest.capabilities.map((c) => `- ${c}`),
    ``,
    `## Absorb`,
    ``,
    ...manifest.absorb.map((a) => `- ${a}`),
    ``,
    `## Reject`,
    ``,
    ...manifest.reject.map((r) => `- ${r}`),
    ``,
    `## HartOS Compatibility`,
    ``,
    `This pack must be implemented using:`,
    `- Supabase as source of truth`,
    `- HartOS approval gates for any mutations`,
    `- HartOS provisioning engine for deployments`,
    `- No direct production deployment`,
    ``,
    `## Next steps`,
    ``,
    `1. Review adaptation-plan.md`,
    `2. Implement component stubs in components/`,
    `3. Add Supabase migrations if needed in migrations/`,
    `4. Wire Cloudflare/Trigger runtime in runtime/`,
    `5. Run tests/pack.contract.test.ts`,
    `6. Complete smoke/smoke-plan.md`,
    ``,
  ].join("\n") + "\n";
}

function generateAdaptationPlan(capability: string, manifest: PackManifest): string {
  return [
    `# Adaptation Plan: ${capability}`,
    ``,
    `Generated by Beezulbub Phase 11C. Review and complete before implementing.`,
    ``,
    `## What to absorb`,
    ``,
    ...manifest.absorb.map((a) => `- ${a}`),
    ``,
    `## What to reject`,
    ``,
    ...manifest.reject.map((r) => `- ${r}`),
    ``,
    `## HartOS adaptation steps`,
    ``,
    `1. **Identify extractable components** — review source-digest-summary.md`,
    `2. **Remove foreign auth** — HartOS uses Telegram allowlists, not foreign auth`,
    `3. **Replace database assumptions** — all state in Supabase with RLS`,
    `4. **Abstract provider dependencies** — use HartOS provisioning adapters`,
    `5. **Add HartOS-standard tests** — node:test, no secrets in test fixtures`,
    `6. **Create env placeholders** — never hardcode values`,
    `7. **Wire approval gate** — any mutation must require explicit HartOS gate`,
    ``,
    `## Required env vars`,
    ``,
    `List env vars this pack will need (no values here — use .env.example pattern):`,
    `- SUPABASE_URL=`,
    `- SUPABASE_SERVICE_ROLE_KEY=`,
    ``,
    `## Required provider adapters`,
    ``,
    `- supabase (data layer)`,
    `- cloudflare (runtime)`,
    ``,
    `## Security notes`,
    ``,
    `- Never include real API keys in pack files`,
    `- Never include real database URLs`,
    `- All secrets go in env vars, never hardcoded`,
    ``,
  ].join("\n") + "\n";
}

function generateSourceDigestSummary(candidate: ScoreJson): string {
  return [
    `# Source Digest Summary`,
    ``,
    `**Repo:** ${candidate.repoName ?? "unknown"}`,
    `**Verdict:** ${candidate.verdict ?? "UNKNOWN"}`,
    `**Score:** ${candidate.score?.overall ?? 0}/10`,
    `**License:** ${candidate.license ?? "unknown"}`,
    ``,
    `## Capabilities detected`,
    ``,
    ...(candidate.capabilities ?? ["none detected"]).map((c) => `- ${c}`),
    ``,
    `## Summary`,
    ``,
    `${candidate.summary ?? "No summary available."}`,
    ``,
    `---`,
    `This summary is for reference only. No third-party code has been copied.`,
    ``,
  ].join("\n") + "\n";
}

function generateImplementationNotes(capability: string): string {
  return [
    `# Implementation Notes: ${capability}`,
    ``,
    `## TODO before this pack is production-ready`,
    ``,
    `- [ ] Review source-digest-summary.md`,
    `- [ ] Implement component stubs in components/`,
    `- [ ] Add Supabase migrations in migrations/`,
    `- [ ] Add Cloudflare Worker integration in runtime/`,
    `- [ ] Complete tests/pack.contract.test.ts`,
    `- [ ] Complete smoke/smoke-plan.md`,
    `- [ ] Security review — no secrets, RLS applied`,
    `- [ ] Get approval from team lead before production deployment`,
    ``,
    `## Implementation order`,
    ``,
    `1. Data model first (migrations/)`,
    `2. Business logic (runtime/)`,
    `3. Component stubs (components/)`,
    `4. Tests (tests/)`,
    `5. Smoke plan (smoke/)`,
    ``,
    `## HartOS conventions`,
    ``,
    `- Use Supabase RPC instead of raw SQL`,
    `- All mutations behind HartOS approval gates`,
    `- Observability: emit debug_events for every workflow step`,
    `- No hardcoded secrets — env vars only`,
    ``,
  ].join("\n") + "\n";
}

function generatePackContractTest(capability: string): string {
  return [
    `/**`,
    ` * tests/pack.contract.test.ts`,
    ` *`,
    ` * Pack contract test for: ${capability}`,
    ` * Generated by HartOS Beezulbub Phase 11C.`,
    ` * Complete these tests before marking pack as implementation-ready.`,
    ` */`,
    ``,
    `import { test, describe } from "node:test";`,
    `import assert from "node:assert/strict";`,
    `import { existsSync } from "node:fs";`,
    `import { readFile } from "node:fs/promises";`,
    `import path from "node:path";`,
    ``,
    `const packDir = path.dirname(new URL(import.meta.url).pathname);`,
    `const rootDir = path.join(packDir, "..");`,
    ``,
    `describe("${capability} pack contract", () => {`,
    `  test("pack.manifest.json exists and is valid", async () => {`,
    `    const manifestPath = path.join(rootDir, "pack.manifest.json");`,
    `    assert.ok(existsSync(manifestPath), "pack.manifest.json must exist");`,
    `    const raw = await readFile(manifestPath, "utf8");`,
    `    const manifest = JSON.parse(raw);`,
    `    assert.ok(manifest.packName, "manifest must have packName");`,
    `    assert.ok(manifest.packVersion, "manifest must have packVersion");`,
    `    assert.ok(manifest.status, "manifest must have status");`,
    `  });`,
    ``,
    `  test("adaptation-plan.md exists", () => {`,
    `    assert.ok(existsSync(path.join(rootDir, "adaptation-plan.md")));`,
    `  });`,
    ``,
    `  test("no secrets in pack files", async () => {`,
    `    const manifestRaw = await readFile(path.join(rootDir, "pack.manifest.json"), "utf8");`,
    `    const secretPattern = /sk-[A-Za-z0-9_-]{20,}/;`,
    `    assert.ok(!secretPattern.test(manifestRaw), "manifest must not contain secrets");`,
    `  });`,
    ``,
    `  test("smoke plan exists", () => {`,
    `    assert.ok(existsSync(path.join(rootDir, "smoke", "smoke-plan.md")));`,
    `  });`,
    ``,
    `  // TODO: Add capability-specific tests here`,
    `});`,
    ``,
  ].join("\n") + "\n";
}

function generateSmokePlan(capability: string): string {
  return [
    `# Smoke Plan: ${capability}`,
    ``,
    `Complete this before marking pack as production-ready.`,
    ``,
    `## Pre-smoke checklist`,
    ``,
    `- [ ] pack.manifest.json is valid`,
    `- [ ] adaptation-plan.md reviewed`,
    `- [ ] no secrets in any pack file`,
    `- [ ] HartOS approval gate wired`,
    `- [ ] Supabase migrations applied (if any)`,
    ``,
    `## Smoke tests`,
    ``,
    `- [ ] Component renders without errors`,
    `- [ ] No secrets in rendered output`,
    `- [ ] Works with Supabase RLS enabled`,
    `- [ ] Approval gate blocks unauthorized mutations`,
    ``,
    `## Final state proof`,
    ``,
    `Describe exactly what "done" looks like for this capability:`,
    ``,
    `TODO: ${capability} final state proof goes here.`,
    ``,
  ].join("\n") + "\n";
}

function generateTodo(capability: string, manifest: PackManifest): string {
  return [
    `# TODO: ${capability} Pack Implementation`,
    ``,
    `This file was auto-generated by HartOS Beezulbub Phase 11C.`,
    ``,
    `## Critical: Read before implementing`,
    ``,
    `- Review adaptation-plan.md before writing any code`,
    `- Review source-digest-summary.md to understand what was absorbed`,
    `- Review rejected-poison.md to understand what was excluded`,
    `- Never copy third-party code without adaptation`,
    ``,
    `## Capability: ${capability}`,
    ``,
    `Source: ${manifest.source.repoName} (${manifest.source.verdict}, ${manifest.source.scoreOverall}/10)`,
    ``,
    `## Implementation tasks`,
    ``,
    `### 1. Data model`,
    `- [ ] Define Supabase schema in migrations/`,
    `- [ ] Apply CHECK constraints to match TypeScript unions`,
    ``,
    `### 2. Business logic`,
    `- [ ] Implement runtime stubs in runtime/`,
    `- [ ] Add approval gate for any mutations`,
    ``,
    `### 3. Components`,
    `- [ ] Implement component stubs in components/`,
    `- [ ] Wire to Supabase data layer`,
    ``,
    `### 4. Tests`,
    `- [ ] Complete tests/pack.contract.test.ts`,
    `- [ ] Add integration tests`,
    ``,
    `### 5. Smoke`,
    `- [ ] Complete smoke/smoke-plan.md`,
    `- [ ] Prove final state`,
    ``,
    `### 6. Review`,
    `- [ ] Security review`,
    `- [ ] No secrets`,
    `- [ ] HartOS gates applied`,
    ``,
  ].join("\n") + "\n";
}

// ─── Main generator ───────────────────────────────────────────────────────────

export async function generatePack(
  options: PackGenerateOptions,
  reportsDir: string,
  cwd: string,
  registryPath?: string,
  ledgerPath?: string
): Promise<PackGenerateResult> {
  const {
    capability,
    digestPath,
    fromLatest = false,
    approveDevour = false,
    force = false,
    allowPackGenerate = false,
    referencePack = false,
    packOutputDir = DEFAULT_PACKS_DIR,
  } = options;

  // 1. Gate check — requires BOTH flag AND env
  if (!approveDevour || !allowPackGenerate) {
    const missing: string[] = [];
    if (!approveDevour) missing.push("--approve-devour CLI flag");
    if (!allowPackGenerate) missing.push("BEEZULBUB_ALLOW_PACK_GENERATE=true");
    return {
      status: "blocked_missing_approval",
      message:
        `Pack generation requires explicit approval.\n` +
        `Missing: ${missing.join(", ")}\n\n` +
        `Set BEEZULBUB_ALLOW_PACK_GENERATE=true and pass --approve-devour to proceed.`,
    };
  }

  // 2. Load candidate
  let candidate: ScoreJson | null = null;
  if (digestPath && existsSync(digestPath)) {
    try {
      candidate = JSON.parse(await readFile(digestPath, "utf8")) as ScoreJson;
    } catch {
      return { status: "failed", message: `Failed to read digest: ${digestPath}` };
    }
  } else if (fromLatest) {
    candidate = await loadLatestScore(path.join(cwd, reportsDir));
  }

  if (!candidate) {
    return {
      status: "failed",
      message: "No digest found. Run beezulbub:digest or beezulbub:batch first.",
    };
  }

  // 3. Validate verdict
  const verdict = candidate.verdict ?? "UNKNOWN";
  const isDevourable = DEVOURABLE_VERDICTS.has(verdict);
  const isReference = verdict === "REFERENCE_ONLY";

  if (!isDevourable && !(isReference && referencePack)) {
    return {
      status: "blocked_bad_verdict",
      message:
        `Verdict is ${verdict} — pack generation blocked.\n` +
        `Only DEVOUR and PARTIAL_DEVOUR can generate implementation skeletons.\n` +
        `Use --reference-pack for REFERENCE_ONLY verdicts (study-only).`,
    };
  }

  // 4. Determine pack name
  const packName =
    capability ??
    (candidate.capabilities && candidate.capabilities.length > 0
      ? candidate.capabilities[0]!
      : (candidate.repoName ?? "unknown").toLowerCase().replace(/[^a-z0-9]/g, "_"));

  const packsDir = path.isAbsolute(packOutputDir)
    ? packOutputDir
    : path.join(cwd, packOutputDir);
  const packPath = path.join(packsDir, packName);

  // 5. Check overwrite
  if (existsSync(packPath) && !force) {
    return {
      status: "blocked_existing_pack",
      message:
        `Pack already exists: ${packPath}\n` +
        `Use --force to overwrite an existing pack.`,
    };
  }

  // 6. Generate all files
  const manifest = generateManifest(candidate, packName, path.join(cwd, "beezulbub-reports"));
  if (isReference) manifest.status = "reference_only";

  const generatedFiles: Record<string, string> = {
    "pack.manifest.json": JSON.stringify(manifest, null, 2) + "\n",
    "README.md": generateReadme(packName, manifest),
    "adaptation-plan.md": generateAdaptationPlan(packName, manifest),
    "source-digest-summary.md": generateSourceDigestSummary(candidate),
    "rejected-poison.md": formatSafetyIssues([]),
    "implementation-notes.md": generateImplementationNotes(packName),
    "components/README.md": `# Components: ${packName}\n\nComponent stubs go here.\n`,
    "migrations/README.md": `# Migrations: ${packName}\n\nSupabase migrations for this pack go here.\n`,
    "runtime/README.md": `# Runtime: ${packName}\n\nCloudflare Worker / Trigger.dev stubs go here.\n`,
    "tests/pack.contract.test.ts": generatePackContractTest(packName),
    "smoke/smoke-plan.md": generateSmokePlan(packName),
    "TODO.generated.md": generateTodo(packName, manifest),
  };

  // 7. Safety scan
  const safety = scanPackContent(generatedFiles);
  if (!safety.passed) {
    return {
      status: "failed",
      message: `Pack safety scan failed:\n${safety.summary}`,
    };
  }

  // 8. Write files
  await mkdir(packPath, { recursive: true });
  for (const [relPath, content] of Object.entries(generatedFiles)) {
    const fullPath = path.join(packPath, relPath);
    await mkdir(path.dirname(fullPath), { recursive: true });
    await writeFile(fullPath, content, "utf8");
  }

  // 9. Register in capability registry and provenance ledger
  const resolvedRegistry = registryPath
    ? path.resolve(cwd, registryPath)
    : path.resolve(cwd, DEFAULT_REGISTRY_PATH);
  const resolvedLedger = ledgerPath
    ? path.resolve(cwd, ledgerPath)
    : path.resolve(cwd, DEFAULT_LEDGER_PATH);

  try {
    await registerPackGenerated(resolvedRegistry, manifest, packPath);
  } catch {
    // Non-fatal — registry may not exist yet
  }
  try {
    await recordProvenance(resolvedLedger, manifest);
  } catch {
    // Non-fatal — ledger may not exist yet
  }

  return {
    status: "generated",
    packPath,
    packName,
    message: `Pack skeleton generated at: ${packPath}`,
    manifest,
  };
}
