/**
 * src/beezulbub/pack-report.ts
 *
 * Format pack generation reports.
 */

import type { PackGenerateResult, PackPlanResult } from "./pack-types.js";

export function formatPackGenerateReport(result: PackGenerateResult): string {
  const lines = [
    `# Beezulbub Pack Generate Report`,
    ``,
    `Status: **${result.status}**`,
    ``,
    `${result.message}`,
    ``,
  ];

  if (result.manifest) {
    lines.push(`## Generated pack`);
    lines.push(``);
    lines.push(`Pack name: ${result.manifest.packName}`);
    lines.push(`Version: ${result.manifest.packVersion}`);
    lines.push(`Status: ${result.manifest.status}`);
    lines.push(`Source: ${result.manifest.source.repoName} (${result.manifest.source.verdict})`);
    lines.push(`Score: ${result.manifest.source.scoreOverall}/10`);
    lines.push(``);

    if (result.packPath) {
      lines.push(`Path: ${result.packPath}`);
      lines.push(``);
    }

    lines.push(`## Files generated`);
    lines.push(``);
    lines.push(`- pack.manifest.json`);
    lines.push(`- README.md`);
    lines.push(`- adaptation-plan.md`);
    lines.push(`- source-digest-summary.md`);
    lines.push(`- rejected-poison.md`);
    lines.push(`- implementation-notes.md`);
    lines.push(`- components/README.md`);
    lines.push(`- migrations/README.md`);
    lines.push(`- runtime/README.md`);
    lines.push(`- tests/pack.contract.test.ts`);
    lines.push(`- smoke/smoke-plan.md`);
    lines.push(`- TODO.generated.md`);
    lines.push(``);

    lines.push(`## Next steps`);
    lines.push(``);
    lines.push(`1. Review adaptation-plan.md`);
    lines.push(`2. Complete TODO.generated.md tasks`);
    lines.push(`3. Run: npm run beezulbub:pack-list`);
  }

  lines.push(``);
  lines.push(`---`);
  lines.push(`Generated by HartOS Beezulbub Phase 11C`);

  return lines.join("\n") + "\n";
}
