/**
 * src/beezulbub/report.ts
 *
 * Format and write Beezulbub digestion reports.
 * NEVER include raw secrets in any output.
 */

import { writeFile, mkdir, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import type { RepoDigest } from "./types.js";
import { formatScore } from "./score.js";
import { summarisePoisonFlags } from "./poison-filter.js";

const SECRET_PATTERNS = [
  /sk-[A-Za-z0-9_-]{20,}/,
  /eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}/,
  /[A-Za-z0-9_-]{40,}/,
];

export function assertNoSecretsInBeezulbubReport(content: string): void {
  for (const pattern of SECRET_PATTERNS) {
    if (pattern.test(content)) {
      throw new Error(
        "Secret-looking value in Beezulbub report. Report generation aborted."
      );
    }
  }
}

function verdictIcon(verdict: RepoDigest["recommendedVerdict"]): string {
  switch (verdict) {
    case "DEVOUR": return "🦖 DEVOUR";
    case "PARTIAL_DEVOUR": return "🔪 PARTIAL_DEVOUR";
    case "REFERENCE_ONLY": return "👁 REFERENCE_ONLY";
    case "REJECT_POISON": return "☠️ REJECT_POISON";
    case "REJECT_LICENSE": return "⛔ REJECT_LICENSE";
    case "REJECT_STALE": return "💤 REJECT_STALE";
    case "REJECT_LOW_VALUE": return "👎 REJECT_LOW_VALUE";
  }
}

export function formatDigestReport(digest: RepoDigest): string {
  const lines = [
    `# Beezulbub Digest: ${digest.repoName}`,
    ``,
    `**Verdict: ${verdictIcon(digest.recommendedVerdict)}**`,
    ``,
    `Digested: ${digest.digestedAt}`,
    digest.localPath ? `Path: ${digest.localPath}` : "",
    digest.sourceUrl ? `Source: ${digest.sourceUrl}` : "",
    ``,
    `## Stack`,
    ``,
    `Detected stack: ${digest.detectedStack.join(", ") || "unknown"}`,
    `Frameworks: ${digest.frameworks.join(", ") || "none detected"}`,
    `Package managers: ${digest.packageManagers.join(", ") || "none"}`,
    `License: ${digest.license ?? "NONE FOUND"} (risk: ${digest.licenseRisk})`,
    `Tests: ${digest.testPresence}`,
    `Env handling: ${digest.envHandling}`,
    ``,
    `## Score`,
    ``,
    formatScore(digest.score),
    ``,
    `## Poison flags (${digest.poisonFlags.length})`,
    ``,
    summarisePoisonFlags(digest.poisonFlags),
    ``,
  ];

  for (const flag of digest.poisonFlags) {
    lines.push(`- [${flag.severity.toUpperCase()}] ${flag.type}: ${flag.description}`);
    if (flag.location) lines.push(`  Location: ${flag.location}`);
    lines.push(`  → ${flag.recommendation}`);
  }
  if (digest.poisonFlags.length === 0) lines.push("No poison detected.");
  lines.push(``);

  lines.push(`## Extractable capabilities (${digest.usefulCapabilities.length})`);
  lines.push(``);
  for (const cap of digest.usefulCapabilities) {
    lines.push(`### ${cap.name} → ${cap.hartosPackTarget}`);
    lines.push(`${cap.description}`);
    lines.push(`Effort: ${cap.estimatedEffort}`);
    lines.push(`Absorb: ${cap.absorb.join(", ")}`);
    lines.push(`Reject: ${cap.reject.join(", ")}`);
    if (cap.securityNotes.length > 0) {
      lines.push(`Security: ${cap.securityNotes.join("; ")}`);
    }
    lines.push(``);
  }
  if (digest.usefulCapabilities.length === 0) {
    lines.push("No extractable capabilities detected.");
    lines.push(``);
  }

  lines.push(`## HartOS Adaptation Plan`);
  lines.push(``);
  const plan = digest.hartosAdaptationPlan;
  lines.push(`**Target pack:** ${plan.targetPack}`);
  lines.push(``);
  lines.push(`**Absorb:**`);
  for (const a of plan.absorb) lines.push(`  - ${a}`);
  lines.push(``);
  lines.push(`**Reject:**`);
  for (const r of plan.reject) lines.push(`  - ${r}`);
  lines.push(``);
  lines.push(`**Adapt steps:**`);
  for (const s of plan.adaptSteps) lines.push(`  ${s}`);
  lines.push(``);

  if (plan.requiredTests.length > 0) {
    lines.push(`**Required tests:** ${plan.requiredTests.join(", ")}`);
  }
  if (plan.requiredEnvVars.length > 0) {
    lines.push(`**Required env vars:** ${plan.requiredEnvVars.join(", ")}`);
  }
  if (plan.requiredProviderAdapters.length > 0) {
    lines.push(`**Provider adapters:** ${plan.requiredProviderAdapters.join(", ")}`);
  }
  if (plan.requiredSmokeChecks.length > 0) {
    lines.push(`**Smoke checks:** ${plan.requiredSmokeChecks.join("; ")}`);
  }
  if (plan.securityNotes.length > 0) {
    lines.push(`**Security notes:** ${plan.securityNotes.join("; ")}`);
  }
  lines.push(``);

  lines.push(`## Summary`);
  lines.push(``);
  lines.push(digest.summary);
  lines.push(``);
  lines.push(`---`);
  lines.push(`Generated by HartOS Beezulbub Phase 11A`);

  return lines.filter((l) => l !== undefined).join("\n") + "\n";
}

export async function writeDigestReport(
  digest: RepoDigest,
  reportsDir: string
): Promise<{ mdPath: string; jsonPath: string }> {
  const formatted = formatDigestReport(digest);
  assertNoSecretsInBeezulbubReport(formatted);

  await mkdir(reportsDir, { recursive: true });

  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  const mdPath = path.join(reportsDir, `digest-${ts}.md`);
  const jsonPath = path.join(reportsDir, `score-${ts}.json`);

  await writeFile(mdPath, formatted, "utf8");

  // Safe JSON: no raw env values, no secrets
  const safeJson = {
    repoName: digest.repoName,
    digestedAt: digest.digestedAt,
    verdict: digest.recommendedVerdict,
    score: digest.score,
    licenseRisk: digest.licenseRisk,
    testPresence: digest.testPresence,
    envHandling: digest.envHandling,
    poisonFlagCount: digest.poisonFlags.length,
    capabilityCount: digest.usefulCapabilities.length,
    capabilities: digest.usefulCapabilities.map((c) => c.id),
    targetPack: digest.hartosAdaptationPlan.targetPack,
    summary: digest.summary,
  };
  await writeFile(jsonPath, JSON.stringify(safeJson, null, 2) + "\n", "utf8");

  return { mdPath, jsonPath };
}

/** Show the latest digest report from the reports directory */
export async function showLatestReport(reportsDir: string): Promise<string | null> {
  if (!existsSync(reportsDir)) return null;
  const files = (await readdir(reportsDir))
    .filter((f) => f.startsWith("digest-") && f.endsWith(".md"))
    .sort()
    .reverse();
  if (files.length === 0) return null;
  return path.join(reportsDir, files[0]!);
}
