/**
 * src/command-center/command-center-report.ts
 *
 * Formats and writes Command Center reports (Phase 11G). All reports are
 * deterministic, local, and secret-safe. Reports are written under
 * command-center-reports/ as markdown with optional JSON sidecars.
 *
 * NEVER include raw secrets in any output.
 */

import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import type {
  ActionId,
  CardDefinition,
  CardReadModel,
  CockpitPlan,
  DataContract,
} from "./command-center-types.js";
import { ACTION_STATES } from "./action-contract.js";

export const DEFAULT_REPORTS_DIR = "command-center-reports";

const SECRET_PATTERNS = [
  /sk-[A-Za-z0-9_-]{20,}/,
  /eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}/,
  /gh[pousr]_[A-Za-z0-9_]{20,}/,
  /xox[baprs]-[A-Za-z0-9-]{20,}/,
];

export function assertNoSecretsInReport(content: string): void {
  for (const pattern of SECRET_PATTERNS) {
    if (pattern.test(content)) {
      throw new Error("Secret-looking value in Command Center report. Report generation aborted.");
    }
  }
}

function bullets(items: string[], emptyText = "none"): string[] {
  if (items.length === 0) return [`- ${emptyText}`];
  return items.map((i) => `- ${i}`);
}

function actionsInState(state: string): ActionId[] {
  return (Object.keys(ACTION_STATES) as ActionId[]).filter((a) => ACTION_STATES[a] === state).sort();
}

// ─── Data contract report ─────────────────────────────────────────────────────

export function formatDataContractReport(contract: DataContract, readModels: CardReadModel[]): string {
  const missing = new Set<string>();
  for (const rm of readModels) for (const m of rm.missingSources) missing.add(m);

  const blocked = actionsInState("forbidden");
  const approval = actionsInState("approval_required");
  const manual = actionsInState("manual_required");
  const readOnly = actionsInState("read_only");

  const lines = [
    "# Command Center Data Contract",
    "",
    `Generated: ${contract.generatedAt}`,
    "",
    "> Orchestrator is the brain. Command Center is a read/control surface.",
    "> Phase 11G defines the contract only — it does not build UI and does not mutate providers/Supabase/packs.",
    "",
    "## Summary",
    "",
    `- Card count: ${contract.cardCount}`,
    `- Card groups: ${contract.groups.join(", ")}`,
    `- Read-only actions: ${readOnly.join(", ")}`,
    `- Approval-required actions: ${approval.join(", ") || "none"}`,
    `- Manual-required actions: ${manual.join(", ") || "none"}`,
    `- Forbidden / blocked actions: ${blocked.join(", ") || "none"}`,
    "",
    "## Allowed local source roots",
    "",
    ...bullets(contract.allowedSourceRoots),
    "",
    "## Missing sources (degraded safely)",
    "",
    ...bullets([...missing].sort()),
    "",
    "## Cards",
    "",
  ];

  for (const card of contract.cards) {
    const rm = readModels.find((r) => r.cardId === card.id);
    lines.push(`### ${card.id} (${card.group})`);
    lines.push(`- Title: ${card.title}`);
    lines.push(`- Source: ${card.sourceType} → ${card.sourcePaths.join(", ") || "(derived)"}`);
    lines.push(`- Freshness: ${card.freshnessPolicy}`);
    lines.push(`- Risk: ${card.riskLevel}`);
    lines.push(`- Requires approval: ${card.requiresApproval ? "yes" : "no"}`);
    lines.push(`- Allowed actions: ${card.allowedActions.join(", ")}`);
    lines.push(`- Blocked actions: ${card.blockedActions.join(", ")}`);
    if (rm) lines.push(`- Status: ${rm.status} (confidence: ${rm.confidence})`);
    lines.push("");
  }

  lines.push("---", "Generated by HartOS Command Center Phase 11G (local, deterministic, no mutation).");
  return lines.join("\n") + "\n";
}

// ─── Card registry report ─────────────────────────────────────────────────────

export function formatCardRegistryReport(cards: CardDefinition[], readModels: CardReadModel[]): string {
  const byGroup = new Map<string, CardDefinition[]>();
  for (const card of cards) {
    const list = byGroup.get(card.group) ?? [];
    list.push(card);
    byGroup.set(card.group, list);
  }

  const lines = [
    "# Command Center Card Registry",
    "",
    `Generated: ${new Date().toISOString()}`,
    "",
    `Card count: ${cards.length}`,
    "",
    "> Orchestrator is the brain. Command Center is a read/control surface.",
    "",
  ];

  for (const [group, list] of byGroup) {
    lines.push(`## ${group}`, "");
    for (const card of list) {
      const rm = readModels.find((r) => r.cardId === card.id);
      lines.push(
        `- **${card.id}** — ${card.title} | risk: ${card.riskLevel} | status: ${rm?.status ?? "n/a"} | approval: ${card.requiresApproval ? "yes" : "no"}`
      );
    }
    lines.push("");
  }

  lines.push("---", "Generated by HartOS Command Center Phase 11G.");
  return lines.join("\n") + "\n";
}

// ─── Cockpit plan report ─────────────────────────────────────────────────────

export function formatCockpitPlanReport(plan: CockpitPlan): string {
  const lines = [
    "# Command Center Cockpit Plan",
    "",
    `Generated: ${plan.generatedAt}`,
    "",
    "> Phase 11G does not build UI. This is the planning layer for a future cockpit.",
    "",
    "## Next recommended command",
    "",
    "```bash",
    plan.nextRecommendedCommand,
    "```",
    "",
    "## Action states",
    "",
    `- Read-only: ${plan.readOnlyActions.join(", ")}`,
    `- Approval-required: ${plan.approvalRequiredActions.join(", ") || "none"}`,
    `- Manual-required: ${plan.manualRequiredActions.join(", ") || "none"}`,
    `- Forbidden: ${plan.forbiddenActions.join(", ") || "none"}`,
    "",
    "## Missing sources",
    "",
    ...bullets(plan.missingSources),
    "",
    "## Future cockpit phases",
    "",
  ];
  for (const phase of plan.futurePhases) {
    lines.push(`- **${phase.id}** — ${phase.title}: ${phase.description}`);
  }
  lines.push("", "---", "Generated by HartOS Command Center Phase 11G.");
  return lines.join("\n") + "\n";
}

// ─── Writers ───────────────────────────────────────────────────────────────────

export type CommandCenterReportKind = "data-contract" | "card-registry" | "cockpit-plan";

function timestamp(): string {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

export async function writeReport(
  reportsDir: string,
  kind: CommandCenterReportKind,
  content: string
): Promise<string> {
  assertNoSecretsInReport(content);
  await mkdir(reportsDir, { recursive: true });
  const filePath = path.join(reportsDir, `${kind}-${timestamp()}.md`);
  await writeFile(filePath, content, "utf8");
  return filePath;
}

export async function writeSidecar(
  reportsDir: string,
  kind: CommandCenterReportKind,
  data: unknown
): Promise<string> {
  const content = JSON.stringify(data, null, 2) + "\n";
  assertNoSecretsInReport(content);
  await mkdir(reportsDir, { recursive: true });
  const filePath = path.join(reportsDir, `${kind}-${timestamp()}.json`);
  await writeFile(filePath, content, "utf8");
  return filePath;
}
