/**
 * src/cockpit/cockpit-report.ts
 *
 * Formats and writes cockpit reports + thread files. All output is local,
 * deterministic, and secret-safe. Snapshots go under cockpit-reports/; threads
 * go under cockpit-threads/.
 *
 * NEVER include raw secrets in any output.
 */

import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import type {
  CockpitState,
  CockpitOrchestratorResponse,
  CockpitThread,
} from "./cockpit-types.js";
import { looksLikeSecret } from "./cockpit-state.js";

export const DEFAULT_COCKPIT_REPORTS_DIR = "cockpit-reports";
export const DEFAULT_COCKPIT_THREADS_DIR = "cockpit-threads";

export function assertNoSecretsInReport(content: string): void {
  if (looksLikeSecret(content)) {
    throw new Error("Secret-looking value in cockpit report. Report generation aborted.");
  }
}

function bullets(items: string[], emptyText = "none"): string[] {
  if (items.length === 0) return [`- ${emptyText}`];
  return items.map((i) => `- ${i}`);
}

function timestamp(now: Date = new Date()): string {
  return now.toISOString().replace(/[:.]/g, "-");
}

// ─── Snapshot report ──────────────────────────────────────────────────────────

export function formatSnapshotReport(state: CockpitState): string {
  const s = state.summary;
  const lines = [
    "# HartOS Local Visible Cockpit — Snapshot",
    "",
    `Generated: ${state.generatedAt}`,
    `Mode: ${state.mode}`,
    "",
    "> Orchestrator = brain. Command Center contract = nervous system. Cockpit = visible control surface.",
    "> Phase 11H is local-only. No provider mutation, no Supabase mutation, no pack mutation, no deploys, no network.",
    "",
    "## System summary",
    "",
    `- Card count: ${s.cardCount}`,
    `- Card groups: ${s.groups.join(", ")}`,
    `- Missing sources: ${s.missingSourceCount}`,
    `- Read-only actions: ${s.readOnlyActionCount}`,
    `- Approval-required actions: ${s.approvalRequiredActionCount}`,
    `- Manual-required actions: ${s.manualRequiredActionCount}`,
    `- Forbidden actions: ${s.forbiddenActionCount}`,
    `- Reports available: ${s.reportCount}`,
    `- Latest request: ${s.latestRequest ?? "(none)"}`,
    `- Latest strategy verdict: ${s.latestStrategyVerdict ?? "n/a"}`,
    `- Latest CTO verdict: ${s.latestCtoVerdict ?? "n/a"}`,
    `- Next recommended command: ${s.nextRecommendedCommand}`,
    "",
    "## Card groups",
    "",
  ];

  for (const group of state.groups) {
    lines.push(`### ${group.title} (${group.group})`, "");
    for (const card of group.cards) {
      lines.push(`- **${card.id}** — ${card.title} | risk: ${card.riskLevel} | status: ${card.status} (${card.confidence})`);
    }
    lines.push("");
  }

  lines.push("## Missing sources", "", ...bullets(state.missingSources), "");
  lines.push("## Forbidden / blocked actions", "", ...bullets(state.forbiddenActions), "");
  lines.push("## Approval-required actions", "", ...bullets(state.approvalRequiredActions), "");
  lines.push("## Read-only actions", "", ...bullets(state.readOnlyActions), "");

  lines.push("## Latest local reports", "");
  lines.push(...bullets(state.reports.slice(0, 25).map((r) => r.relativePath)));
  lines.push("");

  if (state.latestResponse) {
    const r = state.latestResponse;
    lines.push("## Latest Orchestrator response", "");
    lines.push(`- Request: ${r.request}`);
    lines.push(`- Classification: ${r.classification.classification}`);
    lines.push(`- Strategy: ${r.strategyReview ?? "n/a"}`);
    lines.push(`- CTO: ${r.ctoReview ?? "n/a"}`);
    lines.push(`- Next command: ${r.nextRecommendedCommand}`);
    lines.push("");
  }

  lines.push("---", "Generated by HartOS Local Visible Cockpit Phase 11H (local, deterministic, no mutation).");
  return lines.join("\n") + "\n";
}

// ─── Thread report ────────────────────────────────────────────────────────────

export function formatThreadReport(response: CockpitOrchestratorResponse): string {
  const lines = [
    "# HartOS Cockpit Thread",
    "",
    `Generated: ${response.createdAt}`,
    `Thread: ${response.threadId}`,
    `Request id: ${response.requestId}`,
    "",
    "## Request",
    "",
    response.request,
    "",
    "## Orchestrator response",
    "",
    `- Classification: ${response.classification.classification} (domain: ${response.classification.domain}, risk: ${response.classification.riskLevel})`,
    `- Recommended specialist: ${response.classification.recommendedSpecialist}`,
    `- Strategy review: ${response.strategyReview ?? "n/a"}`,
    `- CTO review: ${response.ctoReview ?? "n/a"}`,
    `- Capability gaps: ${response.capabilityGaps}`,
    `- Build plan: ${response.buildPlanSummary}`,
    `- Handover: ${response.handoverPath ?? "(none)"}`,
    `- Next recommended command: ${response.nextRecommendedCommand}`,
    "",
    "## Report paths",
    "",
    ...bullets(response.reportPaths),
    "",
    "## Blocked actions (not executable from cockpit)",
    "",
    ...bullets(response.blockedActions),
    "",
    "## Approval-required actions (non-executable from cockpit)",
    "",
    ...bullets(response.approvalRequiredActions),
    "",
    "---",
    "Generated by HartOS Cockpit Phase 11H. The cockpit recommends; it never executes.",
  ];
  return lines.join("\n") + "\n";
}

// ─── Writers ───────────────────────────────────────────────────────────────────

export async function writeSnapshotReport(
  reportsDir: string,
  state: CockpitState,
  now: Date = new Date()
): Promise<{ mdPath: string; jsonPath: string }> {
  const md = formatSnapshotReport(state);
  const json = JSON.stringify(state, null, 2) + "\n";
  assertNoSecretsInReport(md);
  assertNoSecretsInReport(json);
  await mkdir(reportsDir, { recursive: true });
  const ts = timestamp(now);
  const mdPath = path.join(reportsDir, `cockpit-snapshot-${ts}.md`);
  const jsonPath = path.join(reportsDir, `cockpit-snapshot-${ts}.json`);
  await writeFile(mdPath, md, "utf8");
  await writeFile(jsonPath, json, "utf8");
  return { mdPath, jsonPath };
}

export async function writeThreadReport(
  reportsDir: string,
  response: CockpitOrchestratorResponse,
  now: Date = new Date()
): Promise<{ mdPath: string; jsonPath: string }> {
  const md = formatThreadReport(response);
  const json = JSON.stringify(response, null, 2) + "\n";
  assertNoSecretsInReport(md);
  assertNoSecretsInReport(json);
  await mkdir(reportsDir, { recursive: true });
  const ts = timestamp(now);
  const mdPath = path.join(reportsDir, `cockpit-thread-${ts}.md`);
  const jsonPath = path.join(reportsDir, `cockpit-thread-${ts}.json`);
  await writeFile(mdPath, md, "utf8");
  await writeFile(jsonPath, json, "utf8");
  return { mdPath, jsonPath };
}

export async function writeThreadFile(
  threadsDir: string,
  thread: CockpitThread
): Promise<string> {
  const json = JSON.stringify(thread, null, 2) + "\n";
  assertNoSecretsInReport(json);
  await mkdir(threadsDir, { recursive: true });
  const filePath = path.join(threadsDir, `${thread.threadId}.json`);
  await writeFile(filePath, json, "utf8");
  return filePath;
}

export async function writeMessageFile(
  threadsDir: string,
  response: CockpitOrchestratorResponse
): Promise<string> {
  const json = JSON.stringify(response, null, 2) + "\n";
  assertNoSecretsInReport(json);
  await mkdir(threadsDir, { recursive: true });
  const filePath = path.join(threadsDir, `message-${response.requestId}.json`);
  await writeFile(filePath, json, "utf8");
  return filePath;
}
