/**
 * Deployment Report Builder
 *
 * Builds structured reports for staging and production deployments.
 * Reports are written to the filesystem — never to external services.
 *
 * Security rules:
 *   - Reports MUST NOT contain secret values.
 *   - Reports MUST NOT contain raw API keys or tokens.
 *   - Reports contain only: filenames, status flags, timestamps, notes.
 */

import { writeFile } from "node:fs/promises";

export type DeploymentEnvironment = "local" | "staging" | "production";

export interface DeploymentReport {
  agentName: string;
  environment: DeploymentEnvironment;
  timestamp: string;
  migrationsApplied: string[];
  migrationsPending: string[];
  migrationErrors: string[];
  cloudflareDeployed: boolean;
  cloudflareHealthy: boolean | null;
  telegramWebhookRegistered: boolean;
  triggerReady: boolean | null;
  smokeTestPassed: boolean | null;
  smokeTestNotes: string[];
  notes: string[];
  warnings: string[];
}

export function buildDeploymentReport(
  params: Partial<DeploymentReport> &
    Pick<DeploymentReport, "agentName" | "environment">
): DeploymentReport {
  return {
    timestamp: new Date().toISOString(),
    migrationsApplied: [],
    migrationsPending: [],
    migrationErrors: [],
    cloudflareDeployed: false,
    cloudflareHealthy: null,
    telegramWebhookRegistered: false,
    triggerReady: null,
    smokeTestPassed: null,
    smokeTestNotes: [],
    notes: [],
    warnings: [],
    ...params,
  };
}

const SECRET_PATTERNS = [
  /sk-[A-Za-z0-9_-]{20,}/,
  /eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}/,
  /[A-Za-z0-9_-]{40,}/,
];

/** Assert that a report string contains no secret-looking values before writing. */
export function assertNoSecrets(report: string): void {
  for (const pattern of SECRET_PATTERNS) {
    if (pattern.test(report)) {
      throw new Error(
        "Secret-looking value detected in deployment report. " +
          "Report generation aborted. Check that no env values were included."
      );
    }
  }
}

export function formatDeploymentReport(report: DeploymentReport): string {
  const status = (v: boolean | null) =>
    v === null ? "not run" : v ? "✓ yes" : "✗ no";

  const lines: string[] = [
    `# Deployment Report: ${report.agentName}`,
    ``,
    `Environment: ${report.environment}`,
    `Timestamp:   ${report.timestamp}`,
    ``,
    `## Migrations`,
    `Applied: ${report.migrationsApplied.length}`,
    ...report.migrationsApplied.map((f) => `  - ${f}`),
    `Pending: ${report.migrationsPending.length}`,
    ...report.migrationsPending.map((f) => `  - ${f}`),
    ...(report.migrationErrors.length > 0
      ? ["Errors:", ...report.migrationErrors.map((e) => `  - ERROR: ${e}`)]
      : []),
    ``,
    `## Provider deployment`,
    `Cloudflare deployed: ${status(report.cloudflareDeployed)}`,
    `Cloudflare health:   ${status(report.cloudflareHealthy)}`,
    `Telegram webhook:    ${status(report.telegramWebhookRegistered)}`,
    `Trigger ready:       ${status(report.triggerReady)}`,
    ``,
    `## Smoke test`,
    `Passed: ${status(report.smokeTestPassed)}`,
    ...report.smokeTestNotes.map((n) => `  - ${n}`),
    ``,
  ];

  if (report.warnings.length > 0) {
    lines.push(`## Warnings`);
    for (const w of report.warnings) lines.push(`  ⚠ ${w}`);
    lines.push(``);
  }

  if (report.notes.length > 0) {
    lines.push(`## Notes`);
    for (const n of report.notes) lines.push(`  - ${n}`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`Generated by HartOS Agent Factory v2 Phase 5`);

  return lines.join("\n") + "\n";
}

/** Write report to filesystem. Never writes to external services. */
export async function writeDeploymentReport(
  report: DeploymentReport,
  outputPath: string
): Promise<void> {
  const formatted = formatDeploymentReport(report);
  assertNoSecrets(formatted);
  await writeFile(outputPath, formatted, "utf8");
}
