/**
 * src/factory/data-source-generator.ts — T6: generate the agent DATA SOURCE the factory can't.
 *
 * Today a created agent ships a DISABLED generic monitor (archetype-monitoring: type "other",
 * enabled:false, pointing at a get_<name>_overview RPC that does not exist). The runway's step 6 is
 * explicit: "Hand-wire the data source + a type-specific cockpit adapter — engineering, not a flag."
 * This module generates that missing half: from a declared Supabase-RPC spec it emits
 *   (1) a FUNCTIONAL, self-contained read-only overview RESOLVER (TypeScript) that calls the RPC and
 *       maps named columns → cockpit overview metrics, with honest empty-state handling, and
 *   (2) an ENABLED read-model config (the functional upgrade of the disabled archetype).
 *
 * The resolver takes an injected RpcCaller, so it has NO SDK dependency and compiles standalone —
 * which means the T5 typecheck verifier can prove the generated code is green before it is offered
 * for review. Pure + deterministic; no fs/network (the caller writes the artifact for review, never
 * into a repo, never auto-merged). Bounded to the "declared RPC → read-only overview" shape — not
 * arbitrary domains; honest about that scope.
 */

export interface OverviewMetricSpec {
  /** Stable key for the metric. */
  key: string;
  /** Human label for the cockpit card. */
  label: string;
  /** The RPC row column this metric reads. */
  column: string;
}

export interface DataSourceSpec {
  agentName: string;
  /** The Supabase read-only RPC the monitor calls (defaults to get_<slug>_overview). */
  rpc?: string;
  /** The column carrying the row freshness timestamp (default "updated_at"). */
  freshnessColumn?: string;
  metrics: OverviewMetricSpec[];
}

export interface GeneratedDataSource {
  slug: string;
  rpc: string;
  /** The self-contained resolver module (TypeScript source). */
  module: string;
  /** An ENABLED, read-only read-model config (functional upgrade of the disabled archetype). */
  readModel: {
    id: string;
    type: string;
    enabled: true;
    mode: "supabase_readonly";
    allowedRpcs: string[];
    allowedTables: string[];
  };
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "monitor";
}

function pascal(text: string): string {
  const p = text.replace(/[^a-zA-Z0-9]+/g, " ").trim().split(/\s+/).map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
  return /^[A-Za-z]/.test(p) ? p : `Agent${p}`;
}

export interface SpecViolation {
  field: string;
  detail: string;
}

/** Validate a spec before generating — a bad spec must never produce a misleading source. */
export function validateDataSourceSpec(spec: DataSourceSpec): SpecViolation[] {
  const v: SpecViolation[] = [];
  if (!spec.agentName?.trim()) v.push({ field: "agentName", detail: "agentName is required" });
  if (!Array.isArray(spec.metrics) || spec.metrics.length === 0) v.push({ field: "metrics", detail: "at least one metric is required" });
  const seen = new Set<string>();
  for (const m of spec.metrics ?? []) {
    if (!m.key?.trim()) v.push({ field: "metrics", detail: "a metric is missing key" });
    if (!m.column?.trim()) v.push({ field: "metrics", detail: `metric "${m.key}" is missing column` });
    if (m.key && seen.has(m.key)) v.push({ field: "metrics", detail: `duplicate metric key "${m.key}"` });
    if (m.key) seen.add(m.key);
  }
  return v;
}

/** Generate the functional data-source resolver + an enabled read-model. Pure + deterministic. */
export function generateDataSource(spec: DataSourceSpec): GeneratedDataSource {
  const violations = validateDataSourceSpec(spec);
  if (violations.length > 0) {
    throw new Error(`Invalid data-source spec:\n- ${violations.map((x) => `${x.field}: ${x.detail}`).join("\n- ")}`);
  }
  const slug = slugify(spec.agentName);
  const Name = pascal(spec.agentName);
  const rpc = (spec.rpc ?? `get_${slug.replace(/-/g, "_")}_overview`).trim();
  const fresh = (spec.freshnessColumn ?? "updated_at").trim();

  const metricLines = spec.metrics
    .map((m) => `    { key: ${JSON.stringify(m.key)}, label: ${JSON.stringify(m.label)}, value: latest ? latest[${JSON.stringify(m.column)}] ?? null : null },`)
    .join("\n");

  const module = [
    `// file: ${slug}-overview.ts`,
    `// Generated by the HartOS factory data-source generator (T6). Functional read-only overview`,
    `// resolver for the "${spec.agentName}" agent. Self-contained: inject an RpcCaller (the agent's`,
    `// read-only Supabase RPC transport). No mutation; honest empty-state.`,
    ``,
    `export interface ${Name}OverviewMetric {`,
    `  key: string;`,
    `  label: string;`,
    `  value: unknown;`,
    `}`,
    ``,
    `export interface ${Name}Overview {`,
    `  agent: string;`,
    `  metrics: ${Name}OverviewMetric[];`,
    `  freshAsOf: string | null;`,
    `  empty: boolean;`,
    `}`,
    ``,
    `export type RpcCaller = (rpc: string, args?: Record<string, unknown>) => Promise<Array<Record<string, unknown>>>;`,
    ``,
    `/** Resolve the ${spec.agentName} overview from the read-only RPC "${rpc}". Latest row wins; empty is honest. */`,
    `export async function resolve${Name}Overview(call: RpcCaller, args: Record<string, unknown> = {}): Promise<${Name}Overview> {`,
    `  const rows = await call(${JSON.stringify(rpc)}, args);`,
    `  const latest = rows.length > 0 ? rows[rows.length - 1] ?? null : null;`,
    `  const metrics: ${Name}OverviewMetric[] = [`,
    metricLines,
    `  ];`,
    `  const freshRaw = latest ? latest[${JSON.stringify(fresh)}] : null;`,
    `  return {`,
    `    agent: ${JSON.stringify(spec.agentName)},`,
    `    metrics,`,
    `    freshAsOf: typeof freshRaw === "string" ? freshRaw : null,`,
    `    empty: latest === null,`,
    `  };`,
    `}`,
    ``,
  ].join("\n");

  return {
    slug,
    rpc,
    module,
    readModel: {
      id: slug,
      type: slug.replace(/-/g, "_"),
      enabled: true,
      mode: "supabase_readonly",
      allowedRpcs: [rpc],
      allowedTables: [],
    },
  };
}
