/**
 * src/wolverine/wolverine-fix-proposal.ts
 *
 * The bridge from a Wolverine finding to a GATED FixProposal. PURE + deterministic.
 *
 * A finding that carries a `fixRoute` (its repair maps to an existing gated adapter) becomes a
 * tier-complete `TypedActionProposal` routed to that adapter — so it flows through the SAME
 * proven path the Step-1b canary used: proposal → Hart approves → execution gate (per-action
 * flag + capability token + kill-switch) → adapter mutates → audit → rollback. Wolverine adds
 * NO new authority and NO new mutation primitive; it only proposes. Findings without a fixRoute
 * map to `null` (advisory — Hart fixes them manually). Honest by default.
 *
 * Mirrors src/cockpit/suggestions/suggestion-to-mutation.ts (the suggestion→proposal mapper):
 * non-executable (`executable:false`, `requiredApproval:"Hart"`, a `blockedReason`), every
 * produced proposal passes `assertTierPayloadComplete`, idempotency-key from TRUSTED parts only.
 */

import { makeIdempotencyKey } from "../lib/idempotency-key.js";
import { ADAPTER_ROUTE_KEY, type MutationRoute } from "../cockpit/suggestions/suggestion-to-mutation.js";
import type { DryRunResult, ProposalRisk, TypedActionProposal } from "../cockpit/proposals/proposal-types.js";
import type { WolverineFinding } from "./wolverine-types.js";

function riskFromSeverity(sev: WolverineFinding["severity"]): ProposalRisk {
  return sev === "critical" || sev === "high" ? "high" : sev === "medium" ? "medium" : "low";
}

/** Filesystem-safe proposal id derived from the finding id (ids can contain ':'). */
function fixProposalId(findingId: string): string {
  return `wolverine-fix-${findingId}`.replace(/[^a-zA-Z0-9._-]/g, "-");
}

/** A descriptive (non-executable) dry-run shell — only needed by tiers above T0. */
function makeDryRun(finding: WolverineFinding): DryRunResult {
  return {
    wouldHappen: finding.recommendedFix,
    dataWouldTouch: [finding.blastRadius],
    approvalRequired: "Hart",
    executionDisabledReason:
      "This is a Wolverine FixProposal; execution is gated by the single execution gate and disabled here.",
    futureSetupRequired: ["Hart approves the proposal", "the per-adapter allowlist flag is enabled"],
    executed: false,
  };
}

/**
 * Map a Wolverine finding to a gated FixProposal, or `null` when the finding is advisory-only
 * (no `fixRoute`). The result is tier-complete and routed to the finding's adapter; the
 * dispatcher + execution gate remain the sole place execution is decided. `now` is injected.
 */
export function wolverineFixProposal(finding: WolverineFinding, now: string): TypedActionProposal | null {
  const route = finding.fixRoute;
  if (!route) return null;

  // Idempotency from TRUSTED parts only (adapter code + the finding id + the injected date) —
  // never the free-text title/evidence (idempotency-key.ts rule 2). Same finding, same day = no-op.
  const idempotencyKey = makeIdempotencyKey([route.adapterId, finding.id, now.slice(0, 10)]);

  return {
    id: fixProposalId(finding.id),
    domain: "system",
    actionType: "sync_repair_plan",
    title: `Wolverine fix: ${finding.title}`,
    description: finding.evidence,
    sourceIntent: `wolverine:${finding.source}`,
    proposedPayload: {
      [ADAPTER_ROUTE_KEY]: { adapterId: route.adapterId, tier: route.tier } satisfies MutationRoute,
      ...(route.payload ?? {}),
    },
    expectedEffect: finding.recommendedFix,
    riskLevel: riskFromSeverity(finding.severity),
    requiredApproval: "Hart",
    status: "draft",
    createdAt: now,
    expiresAt: null,
    safetyNotes: [
      "Generated by Wolverine from a system-audit finding — review before approving.",
      "Non-executable: approval does not run it; the dispatcher + execution gate decide execution separately.",
      "Automatic eyes, gated hands — Wolverine detects + proposes, it never repairs.",
    ],
    blockedReason: "Execution is decided solely by the single execution gate; this proposal grants no authority.",
    // T0 needs no dry-run (REQUIRED_PAYLOAD_BY_TIER.T0); higher tiers carry a descriptive shell.
    dryRunResult: route.tier === "T0" ? null : makeDryRun(finding),
    executable: false,
    tier: route.tier,
    targetId: finding.id,
    targetName: finding.ownerAgent ?? finding.title,
    idempotencyKey,
    rollbackOrCorrectionNote: finding.rollbackPath,
  };
}

/** Map a batch of findings to FixProposals, dropping advisory (no-fixRoute) ones. */
export function wolverineFixProposals(findings: WolverineFinding[], now: string): TypedActionProposal[] {
  const out: TypedActionProposal[] = [];
  for (const f of findings) {
    const p = wolverineFixProposal(f, now);
    if (p) out.push(p);
  }
  return out;
}
