/**
 * src/launch/report.ts
 *
 * Format and write staging launch reports.
 * NEVER include raw secrets in any output.
 */

import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import type { LaunchReport, LaunchStatus } from "./types.js";

const SECRET_PATTERNS = [
  /sk-[A-Za-z0-9_-]{20,}/,
  /eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}/,
  /[A-Za-z0-9_-]{40,}/,
];

export function assertNoSecretsInReport(content: string): void {
  for (const pattern of SECRET_PATTERNS) {
    if (pattern.test(content)) {
      throw new Error(
        "Secret-looking value detected in launch report. " +
          "Report generation aborted. Ensure no env values are included."
      );
    }
  }
}

function statusIcon(status: LaunchStatus | string): string {
  switch (status) {
    case "success": return "✅";
    case "partial": return "⚠️";
    case "blocked_missing_gate":
    case "blocked_manual_required": return "🚫";
    case "failed": return "❌";
    default: return "○";
  }
}

function stepIcon(status: string): string {
  switch (status) {
    case "success": return "✓";
    case "manual_required": return "⚒";
    case "gate_missing": return "○";
    case "degraded": return "⚠";
    case "failed": return "✗";
    case "skipped": return "–";
    default: return "?";
  }
}

export function formatLaunchReport(report: LaunchReport): string {
  const lines: string[] = [
    `# Staging Launch Report: ${report.agentName}`,
    ``,
    `Environment:    staging`,
    `Launch status:  ${statusIcon(report.launchStatus)} ${report.launchStatus}`,
    `Timestamp:      ${report.timestamp}`,
    ``,
    `## Summary`,
    ``,
    `${report.safeSummary}`,
    ``,
  ];

  if (report.missingGates.length > 0) {
    lines.push(`## Missing gates`);
    lines.push(`Set these to enable full launch:`);
    for (const gate of report.missingGates) {
      lines.push(`  - ${gate}=true`);
    }
    lines.push(``);
  }

  if (report.manualRequiredSteps.length > 0) {
    lines.push(`## Manual action required`);
    lines.push(`These steps could not be automated:`);
    for (const step of report.manualRequiredSteps) {
      lines.push(`  - ${step}`);
    }
    lines.push(``);
  }

  lines.push(`## Provider steps`);
  lines.push(``);
  for (const step of report.steps) {
    lines.push(`${stepIcon(step.status)} **${step.name}** [${step.status}]`);
    lines.push(`  ${step.message}`);
    if (step.nextAction && step.nextAction !== step.message) {
      lines.push(`  Next: ${step.nextAction}`);
    }
    lines.push(``);
  }

  lines.push(`## Smoke test`);
  lines.push(`Result: ${report.smokeResult}`);
  lines.push(``);

  // Show presence only — full paths contain long timestamps that may trigger secret patterns
  if (report.provisionReportPath) {
    lines.push(`Provision report: written to provision-reports/`);
  }
  if (report.rollbackPlanPath) {
    lines.push(`Rollback plan: written to launch-reports/`);
  }
  lines.push(``);

  lines.push(`## Next action`);
  lines.push(report.nextAction);
  lines.push(``);
  lines.push(`---`);
  lines.push(`Generated by HartOS Agent Factory v2 Phase 8`);

  return lines.join("\n") + "\n";
}

export async function writeLaunchReport(
  report: LaunchReport,
  reportsDir: string
): Promise<{ mdPath: string; jsonPath: string }> {
  const formatted = formatLaunchReport(report);
  assertNoSecretsInReport(formatted);

  await mkdir(reportsDir, { recursive: true });

  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  const mdPath = path.join(reportsDir, `staging-launch-${ts}.md`);
  const jsonPath = path.join(reportsDir, `staging-launch-${ts}.json`);

  await writeFile(mdPath, formatted, "utf8");
  // JSON report: safe subset only (no raw env values)
  const safeJson = {
    agentName: report.agentName,
    environment: report.environment,
    launchStatus: report.launchStatus,
    timestamp: report.timestamp,
    missingGates: report.missingGates,
    manualRequiredSteps: report.manualRequiredSteps,
    smokeResult: report.smokeResult,
    stepSummary: report.steps.map((s) => ({
      id: s.id,
      provider: s.provider,
      status: s.status,
      manualRequired: s.manualRequired,
    })),
    nextAction: report.nextAction,
  };
  await writeFile(jsonPath, JSON.stringify(safeJson, null, 2) + "\n", "utf8");

  return { mdPath, jsonPath };
}

export function buildNextAction(report: LaunchReport): string {
  switch (report.launchStatus) {
    case "success":
      return "Staging launch complete. Review smoke results and promote to production when ready.";
    case "partial":
      return `Complete ${report.manualRequiredSteps.length} manual step(s), then re-run launch:staging.`;
    case "blocked_missing_gate":
      return `Set missing gates (${report.missingGates.slice(0, 3).join(", ")}) and re-run launch:staging.`;
    case "blocked_manual_required":
      return "Complete all manual_required steps via CLI/dashboard, then re-run launch:staging.";
    case "failed":
      return "Fix failed steps, run 'npm run provision:rollback-plan', then re-run launch:staging.";
    default:
      // Phase 9 statuses
      return "Review the launch report and address any blocking issues before retrying.";
  }
}

export function deriveLaunchStatus(
  steps: LaunchReport["steps"],
  smokeResult: LaunchReport["smokeResult"],
  missingGlobalGates: boolean
): LaunchReport["launchStatus"] {
  if (missingGlobalGates) return "blocked_missing_gate";

  const failed = steps.filter((s) => s.status === "failed");
  if (failed.length > 0) return "failed";

  const manual = steps.filter((s) => s.status === "manual_required");
  const mutating = steps.filter((s) => !["skipped", "gate_missing"].includes(s.status));

  if (manual.length > 0 && mutating.length === manual.length) {
    return "blocked_manual_required";
  }

  if (manual.length > 0 || smokeResult === "failed") return "partial";
  if (smokeResult === "passed") return "success";

  return "partial";
}
