/**
 * src/obsidian/obsidian-from-wolverine.ts
 *
 * PURE builder: turn a Wolverine audit report into a "Wolverine Audit Summary" note proposal —
 * one of the 5 starter note types. This is the first concrete bridge from the immune system into
 * the meaning layer: a human-readable, long-form audit record for long-term review/trend, not raw
 * facts. No fs/clock.
 */

import type { WolverineReport } from "../wolverine/wolverine-types.js";
import type { ObsidianNoteProposal } from "./obsidian-types.js";

export function wolverineAuditNote(report: WolverineReport, now: string): ObsidianNoteProposal {
  const day = now.slice(0, 10);
  const b = report.bySeverity;
  const body = [
    `# Wolverine Audit — ${day}`,
    "",
    `**Verdict: ${report.verdict}** — ${report.verdictReason}`,
    "",
    `Findings: ${report.findingCount}  ·  critical ${b.critical} · high ${b.high} · medium ${b.medium} · low ${b.low}`,
    "",
    "## Repair queue (worst first)",
    ...(report.repairQueue.length
      ? report.repairQueue.map(
          (f) => `- **[${f.severity}] ${f.title}**\n    - why: ${f.evidence}\n    - fix: ${f.recommendedFix}`,
        )
      : ["- _Nothing surfaced by the active detectors._"]),
    "",
    "_Generated by Wolverine. Repairs are approval-gated; this note is the meaning-layer record._",
  ].join("\n");

  return {
    title: `Wolverine Audit ${day}`,
    folder: "HartOS/Wolverine Audits",
    noteType: "wolverine_audit_summary",
    tags: ["hartos", "wolverine", "audit", report.verdict.toLowerCase()],
    body,
    sources: ["wolverine:audit"],
    confidence: "high",
    reason: "Periodic Wolverine system-audit summary kept in the vault for long-term review + trend.",
    reviewBy: null,
    relatedAgents: ["Wolverine"],
    relatedProposals: [],
    createdAt: now,
  };
}
