/**
 * src/provisioning/report.ts
 *
 * Format and write provisioning reports.
 * NEVER include raw secrets in any output.
 */

import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import type { ProvisionPlan, ProvisionResult } from "./types.js";

const SECRET_PATTERNS = [
  /sk-[A-Za-z0-9_-]{20,}/,
  /eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}/,
  /[A-Za-z0-9_-]{40,}/,
];

export function assertNoSecrets(content: string): void {
  for (const pattern of SECRET_PATTERNS) {
    if (pattern.test(content)) {
      throw new Error(
        "Secret-looking value detected in provisioning report. " +
          "Report generation aborted. Ensure no env values are included."
      );
    }
  }
}

// ─── Plan format ─────────────────────────────────────────────────────────────

export function formatProvisionPlan(plan: ProvisionPlan): string {
  const lines: string[] = [
    `# Provision Plan: ${plan.agentName}`,
    ``,
    `Environment: ${plan.environment}`,
    `Generated:   ${plan.timestamp}`,
    ``,
    `## Summary`,
    `Total steps:    ${plan.totalSteps}`,
    `Mutating steps: ${plan.mutatingSteps}`,
    `Read-only steps: ${plan.readOnlySteps}`,
    ``,
    `## Steps`,
    ``,
  ];

  for (const step of plan.steps) {
    const mutTag = step.mutation ? "MUTATING" : "read-only";
    const gateTag = step.requiredGate ? `gate: ${step.requiredGate}` : "no gate";
    const rollbackTag = step.rollback ? "rollback: yes" : "rollback: manual";
    const prodTag = step.productionGateRequired ? " + CONFIRM_PRODUCTION_DEPLOY" : "";
    lines.push(`### ${step.id}`);
    lines.push(`Provider:    ${step.provider}`);
    lines.push(`Action:      ${step.action}`);
    lines.push(`Type:        ${mutTag}`);
    lines.push(`Gate:        ${gateTag}${prodTag}`);
    lines.push(`Rollback:    ${rollbackTag}`);
    lines.push(`Description: ${step.description}`);
    lines.push(`Summary:     ${step.safeSummary}`);
    lines.push(``);
  }

  if (plan.mutatingSteps > 0) {
    lines.push(`## To apply mutating steps`);
    lines.push(`Set the required gate env vars and run:`);
    lines.push(`  ALLOW_AUTO_PROVISION=true npm run provision:auto -- --env=${plan.environment}`);
    lines.push(`  (For staging, also: CONFIRM_STAGING_PROVISION=true)`);
    lines.push(`  (For production, also: CONFIRM_PRODUCTION_DEPLOY=true)`);
  }

  return lines.join("\n") + "\n";
}

// ─── Result format ────────────────────────────────────────────────────────────

export function formatProvisionResult(result: ProvisionResult): string {
  const lines: string[] = [
    `# Provision Report: ${result.plan.agentName}`,
    ``,
    `Environment: ${result.plan.environment}`,
    `Generated:   ${result.timestamp}`,
    ``,
    `## Summary`,
    `Success:          ${result.success ? "yes" : "no"}`,
    `Applied:          ${result.appliedCount}`,
    `Verified:         ${result.results.filter((r) => r.status === "verified").length}`,
    `Skipped:          ${result.skippedCount}`,
    `Gate missing:     ${result.gateMissingCount}`,
    `Not implemented:  ${result.notImplementedCount}`,
    `Failed:           ${result.failedCount}`,
    ``,
    `## Step Results`,
    ``,
  ];

  for (const r of result.results) {
    const icon =
      r.status === "applied" || r.status === "verified"
        ? "✓"
        : r.status === "failed"
          ? "✗"
          : "○";
    lines.push(`${icon} [${r.status}] ${r.step.id}`);
    lines.push(`  ${r.message}`);
    lines.push(``);
  }

  if (result.notImplementedCount > 0) {
    lines.push(`## Not implemented in Phase 6`);
    lines.push(
      `${result.notImplementedCount} step(s) returned not_implemented. ` +
        `Real provider apply() adapters will be added in Phase 7.`
    );
    lines.push(``);
  }

  if (result.gateMissingCount > 0) {
    lines.push(`## Missing gates`);
    for (const r of result.results.filter((r) => r.status === "gate_missing")) {
      lines.push(`- ${r.step.id}: ${r.message}`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`Generated by HartOS Agent Factory v2 Phase 6`);

  return lines.join("\n") + "\n";
}

// ─── Write report ─────────────────────────────────────────────────────────────

export async function writeReport(
  reportsDir: string,
  filename: string,
  content: string
): Promise<string> {
  assertNoSecrets(content);
  await mkdir(reportsDir, { recursive: true });
  const outputPath = path.join(reportsDir, filename);
  await writeFile(outputPath, content, "utf8");
  return outputPath;
}

export function makeReportFilename(
  prefix: string,
  environment: string
): string {
  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  return `${prefix}-${environment}-${ts}.md`;
}
