/**
 * src/provisioning/rollback.ts
 *
 * Rollback plan generation from a provision ledger.
 * Phase 6: generates the plan (never executes it).
 * Phase 7: rollback() on adapters will execute steps.
 */

import type { ProvisionLedger, ProvisionEnvironment } from "./types.js";

export interface RollbackPlanOutput {
  agentName: string;
  environment: ProvisionEnvironment;
  timestamp: string;
  steps: RollbackPlanStep[];
  formatted: string;
}

export interface RollbackPlanStep {
  stepId: string;
  provider: string;
  action: string;
  status: string;
  rollbackAvailable: boolean;
  instruction: string;
}

const ROLLBACK_INSTRUCTIONS: Record<string, string> = {
  "create_repo:github": "Delete the GitHub repository manually via GitHub dashboard.",
  "create_project:supabase": "Delete the Supabase project via Supabase dashboard.",
  "apply_migrations:supabase":
    "Write reverting migrations and apply via Supabase CLI or dashboard.",
  "set_secret:cloudflare":
    "Remove the Cloudflare Worker secret: `wrangler secret delete <name>`",
  "deploy_worker:cloudflare":
    "Rollback via wrangler: `wrangler rollback --env <env>` or redeploy previous commit.",
  "register_webhook:telegram":
    "Re-register the previous webhook URL: `ALLOW_TELEGRAM_WEBHOOK_REGISTER=true npm run telegram:register-webhook`",
  "register_task:trigger":
    "Disable the Trigger.dev task via the Trigger.dev dashboard.",
  "verify_model:openai": "No rollback needed — read-only step.",
  "run_smoke:*": "No rollback needed — read-only step.",
};

function getInstruction(action: string, provider: string): string {
  const key = `${action}:${provider}`;
  return (
    ROLLBACK_INSTRUCTIONS[key] ??
    ROLLBACK_INSTRUCTIONS[`${action}:*`] ??
    `Manually reverse ${action} on ${provider}. Consult the ${provider} dashboard.`
  );
}

export function buildRollbackPlan(
  ledger: ProvisionLedger,
  environment: ProvisionEnvironment
): RollbackPlanOutput {
  const timestamp = new Date().toISOString();

  // Only entries for this environment that actually did something
  const relevant = ledger.entries.filter(
    (e) =>
      e.environment === environment &&
      (e.status === "applied" || e.status === "verified")
  );

  const steps: RollbackPlanStep[] = relevant.map((entry) => ({
    stepId: entry.stepId,
    provider: entry.provider,
    action: entry.action,
    status: entry.status,
    rollbackAvailable: entry.rollbackAvailable,
    instruction: getInstruction(entry.action, entry.provider),
  }));

  const lines: string[] = [
    `# Rollback Plan: ${ledger.agentName}`,
    ``,
    `Environment: ${environment}`,
    `Generated:   ${timestamp}`,
    ``,
    `## Note`,
    ``,
    `Phase 6 generates rollback instructions — it does NOT execute them.`,
    `Phase 7 will add rollback() implementations to provider adapters.`,
    ``,
    `Work through each step manually. Each step requires human review.`,
    ``,
    `---`,
    ``,
  ];

  if (steps.length === 0) {
    lines.push(`No applied provisioning steps found in ledger for ${environment}.`);
    lines.push(`Nothing to roll back.`);
  } else {
    lines.push(`## Steps to reverse (newest-first)`);
    lines.push(``);
    for (const step of [...steps].reverse()) {
      lines.push(`### ${step.stepId}`);
      lines.push(`Provider: ${step.provider}`);
      lines.push(`Action:   ${step.action}`);
      lines.push(`Status:   ${step.status}`);
      lines.push(``);
      lines.push(`**Instruction:** ${step.instruction}`);
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(`Generated by HartOS Agent Factory v2 Phase 6`);

  const formatted = lines.join("\n") + "\n";

  return { agentName: ledger.agentName, environment, timestamp, steps, formatted };
}
