/**
 * Migration Runner
 *
 * Handles migration planning, validation, ledger tracking, and reporting.
 * Does NOT execute SQL directly — SQL is applied via Supabase CLI or dashboard.
 * This module owns the migration state machine: pending → applied.
 *
 * Phase 5 design rules:
 *   - Plan mode has no side effects.
 *   - Apply mode requires ALLOW_SUPABASE_MIGRATION_APPLY=true gate (enforced in script).
 *   - Production apply also requires CONFIRM_PRODUCTION_DEPLOY=true (enforced in script).
 *   - Filenames must match the timestamp format — rejects invalid names.
 *   - Duplicate timestamp prefixes are an error.
 *   - Ledger tracks applied migrations without storing secrets.
 */

import { readFile, writeFile, readdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";

// Valid migration filename pattern: one or more digits, underscore, description, .sql
// Examples: 000001_core.sql  20260603120000_add_users.sql  2026060312000000_add_users.sql
// Allows 6–18 digits to cover 6-digit sequential, 14-digit Supabase timestamps, and
// 16-digit timestamp+index variants generated by the factory scaffold.
const FILENAME_PATTERN = /^(\d{6,18})_[a-z0-9_-]+\.sql$/i;

export interface MigrationFile {
  filename: string;
  prefix: string;
  fullPath: string;
}

export interface MigrationPlan {
  environment: string;
  migrationsDir: string;
  all: MigrationFile[];
  applied: string[];
  pending: MigrationFile[];
  errors: string[];
  timestamp: string;
}

export interface MigrationLedger {
  agentName: string;
  environment: string;
  applied: string[];
  lastUpdated: string;
}

export interface MigrationReport {
  agentName: string;
  environment: string;
  timestamp: string;
  migrationsApplied: string[];
  migrationsPending: string[];
  validationErrors: string[];
  reportPath: string;
}

// ─── Filename validation ──────────────────────────────────────────────────────

export function parseMigrationFilename(filename: string): { prefix: string } | null {
  const match = FILENAME_PATTERN.exec(filename);
  return match ? { prefix: match[1]! } : null;
}

export function validateMigrationFiles(filenames: string[]): string[] {
  const errors: string[] = [];
  const seen = new Map<string, string>(); // prefix → filename

  for (const filename of filenames) {
    const parsed = parseMigrationFilename(filename);
    if (!parsed) {
      errors.push(
        `Invalid migration filename: "${filename}". ` +
          `Expected format: NNNNNN_description.sql (digits_name.sql)`
      );
      continue;
    }
    if (seen.has(parsed.prefix)) {
      errors.push(
        `Duplicate timestamp prefix "${parsed.prefix}" in files: ` +
          `"${seen.get(parsed.prefix)}" and "${filename}". ` +
          `Each migration must have a unique timestamp prefix.`
      );
    } else {
      seen.set(parsed.prefix, filename);
    }
  }

  return errors;
}

// ─── Ledger I/O ───────────────────────────────────────────────────────────────

export async function loadLedger(ledgerPath: string): Promise<MigrationLedger | null> {
  if (!existsSync(ledgerPath)) return null;
  const content = await readFile(ledgerPath, "utf8");
  return JSON.parse(content) as MigrationLedger;
}

export async function saveLedger(
  ledgerPath: string,
  ledger: MigrationLedger
): Promise<void> {
  await writeFile(ledgerPath, JSON.stringify(ledger, null, 2) + "\n", "utf8");
}

export async function markApplied(
  ledgerPath: string,
  filenames: string[],
  agentName: string,
  environment: string
): Promise<MigrationLedger> {
  const existing = await loadLedger(ledgerPath);
  const ledger: MigrationLedger = {
    agentName,
    environment,
    applied: [...new Set([...(existing?.applied ?? []), ...filenames])].sort(),
    lastUpdated: new Date().toISOString(),
  };
  await saveLedger(ledgerPath, ledger);
  return ledger;
}

// ─── Planning ────────────────────────────────────────────────────────────────

export async function planMigrations(
  migrationsDir: string,
  ledgerPath: string,
  agentName: string,
  environment: string
): Promise<MigrationPlan> {
  const timestamp = new Date().toISOString();

  if (!existsSync(migrationsDir)) {
    return {
      environment,
      migrationsDir,
      all: [],
      applied: [],
      pending: [],
      errors: [`Migrations directory not found: ${migrationsDir}`],
      timestamp,
    };
  }

  const allFiles = (await readdir(migrationsDir))
    .filter((f) => f.endsWith(".sql"))
    .sort();

  const errors = validateMigrationFiles(allFiles);
  const ledger = await loadLedger(ledgerPath);
  const appliedSet = new Set(ledger?.applied ?? []);

  const all: MigrationFile[] = allFiles
    .filter((f) => parseMigrationFilename(f) !== null)
    .map((f) => ({
      filename: f,
      prefix: parseMigrationFilename(f)!.prefix,
      fullPath: path.join(migrationsDir, f),
    }));

  const applied = all.filter((m) => appliedSet.has(m.filename)).map((m) => m.filename);
  const pending = all.filter((m) => !appliedSet.has(m.filename));

  return { environment, migrationsDir, all, applied, pending, errors, timestamp };
}

// ─── Report generation ───────────────────────────────────────────────────────

export function formatMigrationReport(
  plan: MigrationPlan,
  agentName: string
): string {
  const lines: string[] = [
    `# Migration Report: ${agentName}`,
    `Environment: ${plan.environment}`,
    `Generated: ${plan.timestamp}`,
    `Migrations dir: ${plan.migrationsDir}`,
    "",
    `## Summary`,
    `Total: ${plan.all.length}`,
    `Applied: ${plan.applied.length}`,
    `Pending: ${plan.pending.length}`,
    "",
  ];

  if (plan.errors.length > 0) {
    lines.push("## Validation Errors");
    for (const err of plan.errors) lines.push(`- ERROR: ${err}`);
    lines.push("");
  }

  if (plan.applied.length > 0) {
    lines.push("## Applied migrations");
    for (const f of plan.applied) lines.push(`- ${f}`);
    lines.push("");
  }

  if (plan.pending.length > 0) {
    lines.push("## Pending migrations");
    for (const m of plan.pending) lines.push(`- ${m.filename}`);
    lines.push("");
    lines.push("## Apply instructions");
    lines.push("Option 1 — Supabase CLI (recommended):");
    lines.push("  supabase db push");
    lines.push("");
    lines.push("Option 2 — Script (gated):");
    lines.push("  ALLOW_SUPABASE_MIGRATION_APPLY=true npm run migrations:apply");
    lines.push("");
    lines.push("Option 3 — Dashboard: paste each .sql file into the SQL editor.");
    lines.push("");
  }

  return lines.join("\n");
}
