/**
 * src/agents/agent-manifest-seed.ts — the SEED Agent Manifests for the known core organs.
 *
 * Design: docs/superpowers/specs/2026-06-14-dynamic-agent-registration-cockpit.md.
 *
 * Constitutional requirement (Hart, 2026-06-14): the cockpit is a VISUALIZATION of the source of
 * truth, not a static dashboard. The durable record per agent is an `AgentManifest` (authored on
 * Synapse approval); the DISPLAYED status is DERIVED at read time from manifest + liveness + arming
 * (see `deriveAgentStatus`). This module is the AUTHORED seed: one manifest per pre-existing core
 * organ, mapped from the hand-authored catalog in `meta-agent-registry.ts`. It backfills the
 * `agent_registry` store so the organs that pre-date dynamic registration appear in the cockpit as
 * first-class manifest records — not faked, but seeded from the same honest catalog.
 *
 * PURE DATA — no logic, no node: imports, no network, no clock. It only DESCRIBES. The `lifecycle`
 * here is authored (proven/online organs => "live"; the rest => "approved"); the displayed status is
 * still derived downstream from a liveness read-model, so nothing is shown "live" without health
 * confirmation. Sourced from `meta-agent-registry.ts` (the catalog) — keep the two in step.
 */

import type { AgentManifest } from "./agent-manifest.js";

const SEED_CREATED_AT = "2026-06-14T00:00:00.000Z";

/**
 * One AgentManifest per CORE organ agent, mapped from the catalog in meta-agent-registry.ts.
 *
 * Mapping rules (authored, honest):
 *  - displayName / capabilitySummary / parentId come straight from the catalog entry.
 *  - tier: org-hierarchy depth — T0 root authority (Hart), T1 control brain (orchestrator),
 *    T2 organs reporting to the orchestrator, T3 factory-line sub-agents.
 *  - lifecycle: "live" for proven/online organs (catalog status "live"); else "approved".
 *  - permissions.propose: true everywhere a node can emit a proposal/answer; false for the pure
 *    human gate (Hart) and the inert state/meaning stores (supabase/obsidian) only where they don't
 *    propose. permissions.execute: true ONLY for the gated hands —
 *    wolverine, factory, execution-engine. (fitness + ops are propose-only/advisory: fitness is
 *    read-only per the catalog; ops proposes ClickUp writes that the execution-engine actually runs.)
 *  - armingFlag: wolverine => HARTOS_ALLOW_SELF_MOD; factory => HARTOS_ALLOW_COUNCIL_BUILD_BRIDGE;
 *    beezulbub => HARTOS_ALLOW_BEEZ_SCOUT; else null.
 *  - knownRisks: [] (seed); sourceProposalId / retiredAt: null; createdAt = approvedAt = the seed ts.
 */
export const SEED_AGENT_MANIFESTS: AgentManifest[] = [
  {
    agentId: "hart",
    displayName: "Hart (Human)",
    capabilitySummary: "Approval gate + intent source. States outcomes, approves gated actions; the permanent human-approval floor.",
    parentId: null,
    tier: "T0",
    lifecycle: "live",
    permissions: { propose: false, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "orchestrator",
    displayName: "HartOS Command / Orchestrator",
    capabilitySummary: "The control brain + command surface. Classifies natural-language intent, routes to the right organ, composes the answer (Ask HartOS).",
    parentId: "hart",
    tier: "T1",
    lifecycle: "live",
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "rinnegan",
    displayName: "Rinnegan",
    capabilitySummary: "Context compiler / perception. Assembles a ranked, freshness-tagged briefing from vault dossiers + live facts + memory patterns.",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "live",
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "wolverine",
    displayName: "Wolverine",
    capabilitySummary: "Immune system / auditor. Audits HartOS + the fleet, ranks findings, proposes approval-gated FixProposals; detects + proposes, never the builder.",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "live",
    permissions: { propose: true, execute: true },
    armingFlag: "HARTOS_ALLOW_SELF_MOD",
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "sentinel",
    displayName: "Sentinel",
    capabilitySummary: "Fleet heartbeat / liveness monitor. Folds registry + real evidence into per-agent up/stale/down/unknown verdicts; detects only.",
    parentId: "wolverine",
    tier: "T3",
    lifecycle: "live",
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "prophet",
    displayName: "Prophet",
    capabilitySummary: "Forecaster. Projects the consequence of leaving known issues unaddressed; honest confidence, never a horoscope.",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "live",
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "executive-memory",
    displayName: "Executive Memory",
    capabilitySummary: "Pattern memory across time. Durable compact snapshots -> recurring patterns, trends, lessons; the only layer that sees across time.",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "approved",
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "research",
    displayName: "Research Agent",
    capabilitySummary: "Deep-research analyst. Scopes an inquiry, gathers gated sources, synthesizes cited findings, files a gated dossier; never fabricates.",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "approved",
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "beezulbub",
    displayName: "Beezulbub",
    capabilitySummary: "OSS capability scout. Scouts external repos for capabilities to absorb, rejects poison/risky licenses, files a gated capability dossier.",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "live",
    permissions: { propose: true, execute: false },
    armingFlag: "HARTOS_ALLOW_BEEZ_SCOUT",
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "factory",
    displayName: "Agent Factory",
    capabilitySummary: "Agent builder (config, not code). Interrogates a request into a locked AgentSpec, officiates + simulates, emits a gated build/provision proposal.",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "live",
    permissions: { propose: true, execute: true },
    armingFlag: "HARTOS_ALLOW_COUNCIL_BUILD_BRIDGE",
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "officiator",
    displayName: "Officiator",
    capabilitySummary: "Quality gate / judge. Scores a born agent's manifest across 9 facets -> ADMIT / REVISE / REJECT.",
    parentId: "factory",
    tier: "T3",
    lifecycle: "live",
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "simulator",
    displayName: "Simulator / Replay",
    capabilitySummary: "Behavioral rehearsal. Replays happy + red-team scenarios through a born agent's own boundary gate; proves the boundary bites before admission.",
    parentId: "factory",
    tier: "T3",
    lifecycle: "live",
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "execution-engine",
    displayName: "Execution Engine / Mutation Spine",
    capabilitySummary: "Gated hands. The ONLY path that mutates external state; fail-closed behind capability token + allowlist + kill-switch + audit, default OFF.",
    parentId: "factory",
    tier: "T3",
    lifecycle: "approved",
    permissions: { propose: false, execute: true },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "fitness",
    displayName: "Fitness Agent",
    capabilitySummary: "Recovery / training / nutrition. Reads Apple Health / wearable data, coaches training & recovery, surfaces an advisory verdict.",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "live",
    // Read-only / advisory per the catalog (no own hands; fitness mutations are a separate gated path).
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "ops",
    displayName: "Ops Agent",
    capabilitySummary: "Business execution (ClickUp). Reads task cards, triages risks + quick wins, proposes follow-ups (gated ClickUp mutations via the execution engine).",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "live",
    // Propose-only: ops itself never mutates — gated ClickUp writes run through the execution-engine.
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "supabase",
    displayName: "Supabase / State Store",
    capabilitySummary: "Facts / state / audit. Read-models, proposal spine, executive memory, context pack; read-only from the cockpit, gated writes via Node runners.",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "live",
    permissions: { propose: false, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "obsidian",
    displayName: "Obsidian / Vault",
    capabilitySummary: "Meaning / knowledge. Human-readable dossiers + doctrine + MOCs in a local vault, mirrored to Supabase for the deployed Ask; gated, append-only writes.",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "approved",
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
  {
    agentId: "cockpit",
    displayName: "Cockpit",
    capabilitySummary: "Command surface. The hosted, auth-gated control surface where Hart sees the fleet + issues intent; read-only + propose-only, never executes directly.",
    parentId: "orchestrator",
    tier: "T2",
    lifecycle: "live",
    permissions: { propose: true, execute: false },
    armingFlag: null,
    sourceProposalId: null,
    knownRisks: [],
    createdAt: SEED_CREATED_AT,
    approvedAt: SEED_CREATED_AT,
    retiredAt: null,
  },
];
